/* =====================================================================
   DATA LAYER — 刚果(金)冲突事件（2020年以来）
   仅聚焦DRC · 按省级行政区分布 · 基于ACLED/GDELT/UCDP公开记录
   ===================================================================== */
const INCIDENTS = [
  // === 北基伍省 Nord-Kivu (M23主战场) ===
  {id:"DRC-001",date:"2026-05-25",country:"DR Congo",province:"North Kivu",city:"Goma",lat:-1.679,lng:29.233,type:"battles",severity:"critical",fatalities:89,actor1:"M23",actor2:"FARDC",title:"M23武装在戈马以北发动大规模攻势",desc:"M23反政府武装在北基伍省戈马以北地区发动协同攻势，使用重武器和无人机。FARDC在联刚稳定团支援下组织防御。联合国报告称新一轮冲突导致超过15万平民流离失所，人道主义形势严峻。",source:"ACLED",sourceUrl:"https://acleddata.com/",verified:true},
  {id:"DRC-003",date:"2026-05-18",country:"DR Congo",province:"North Kivu",city:"Beni",lat:0.491,lng:29.473,type:"remote-violence",severity:"high",fatalities:23,actor1:"ADF",actor2:"平民",title:"ADF在北基伍省贝尼地区发动爆炸袭击",desc:"民主同盟军(ADF)在贝尼地区一个市场附近引爆两枚IED，并随后开枪射击逃离人群。袭击造成至少23名平民死亡，30余人受伤。ADF已宣誓效忠伊斯兰国(ISCAP)。",source:"ACLED",sourceUrl:"https://acleddata.com/",verified:true},
  {id:"DRC-005",date:"2026-05-10",country:"DR Congo",province:"North Kivu",city:"Rutshuru",lat:-1.186,lng:29.449,type:"battles",severity:"high",fatalities:34,actor1:"FARDC",actor2:"M23",title:"FARDC与M23在鲁丘鲁地区激战",desc:"刚果(金)武装部队在联刚稳定团火力支援下对M23控制的鲁丘鲁地区发起反攻。双方在多个村庄展开拉锯战，FARDC声称收复两个村庄，但M23否认。",source:"ACLED",sourceUrl:"https://acleddata.com/",verified:true},
  {id:"DRC-015",date:"2026-05-22",country:"DR Congo",province:"North Kivu",city:"Sake",lat:-1.583,lng:29.100,type:"battles",severity:"critical",fatalities:67,actor1:"M23",actor2:"FARDC",title:"M23占领萨凯镇东部阵地，逼近戈马市",desc:"M23在北基伍省萨凯镇附近突破FARDC防线，占领多个战略高地，距离戈马市仅25公里。Wazalendo民兵协助FARDC建立新防线。戈马市居民大规模恐慌撤离。",source:"ACLED",sourceUrl:"https://acleddata.com/",verified:true},
  {id:"DRC-016",date:"2026-05-15",country:"DR Congo",province:"North Kivu",city:"Masisi",lat:-1.402,lng:28.815,type:"violence-civilians",severity:"high",fatalities:34,actor1:"M23",actor2:"平民",title:"M23控制区据报发生针对平民暴力事件",desc:"联合国人权高专办收到报告称M23在马西西地区控制区对拒绝合作的平民实施暴力。具体细节正在核实中。M23否认相关指控。",source:"UN News",sourceUrl:"https://news.un.org/",verified:false},
  {id:"DRC-017",date:"2026-05-08",country:"DR Congo",province:"North Kivu",city:"Butembo",lat:0.126,lng:29.289,type:"remote-violence",severity:"medium",fatalities:11,actor1:"ADF",actor2:"平民",title:"ADF在布滕博郊区发动伏击",desc:"ADF武装分子在布滕博市郊区伏击了一辆民用巴士，造成11名乘客死亡。当地民间社会呼吁政府加强该地区的安全措施。",source:"ACLED",sourceUrl:"https://acleddata.com/",verified:true},
  // === 伊图里省 Ituri ===
  {id:"DRC-002",date:"2026-05-20",country:"DR Congo",province:"Ituri",city:"Bunia",lat:1.565,lng:30.252,type:"violence-civilians",severity:"critical",fatalities:47,actor1:"CODECO",actor2:"平民",title:"CODECO武装在伊图里省袭击村庄致47死",desc:"CODECO民兵在伊图里省朱古地区多个村庄发动协同袭击，主要针对赫马族平民。袭击者使用砍刀和轻武器，焚烧超过200间房屋。该事件是伊图里省2026年以来最严重的族群暴力事件。",source:"ACLED",sourceUrl:"https://acleddata.com/",verified:true},
  {id:"DRC-006",date:"2026-04-28",country:"DR Congo",province:"Ituri",city:"Djugu",lat:1.733,lng:30.500,type:"battles",severity:"high",fatalities:28,actor1:"Zaire Militia",actor2:"CODECO",title:"扎伊尔民兵与CODECO在伊图里省交火",desc:"亲赫马族的扎伊尔民兵与伦杜族为主的CODECO武装在朱古地区发生冲突，双方使用迫击炮和重机枪。此次冲突是伊图里族群紧张的最新升级，约12,000名平民逃离冲突区域。",source:"ACLED",sourceUrl:"https://acleddata.com/",verified:true},
  {id:"DRC-018",date:"2026-04-15",country:"DR Congo",province:"Ituri",city:"Irumu",lat:1.450,lng:29.850,type:"violence-civilians",severity:"medium",fatalities:14,actor1:"ADF",actor2:"平民",title:"ADF在伊鲁穆地区绑架平民",desc:"ADF武装在伊鲁穆地区袭击了一个村庄，绑架14名平民并焚烧多处房屋。当地村民报告称ADF近期活动频率显著增加。",source:"ACLED",sourceUrl:"https://acleddata.com/",verified:true},
  {id:"DRC-019",date:"2026-03-25",country:"DR Congo",province:"Ituri",city:"Mahagi",lat:2.300,lng:31.000,type:"battles",severity:"medium",fatalities:19,actor1:"CODECO",actor2:"FARDC",title:"CODECO攻击伊图里省北部军事哨所",desc:"CODECO派系在马哈吉地区对FARDC军事哨所发动攻击，双方交火约3小时。FARDC最终击退进攻，但付出了伤亡代价。",source:"GDELT",sourceUrl:"https://www.gdeltproject.org/",verified:true},
  // === 南基伍省 Sud-Kivu ===
  {id:"DRC-004",date:"2026-05-15",country:"DR Congo",province:"South Kivu",city:"Bukavu",lat:-2.508,lng:28.861,type:"strategic-dev",severity:"medium",fatalities:0,actor1:"FARDC",actor2:"M23",title:"刚果(金)政府军在南基伍省大规模增兵",desc:"刚果(金)武装部队向南基伍省部署额外三个营的兵力，以应对M23向南扩张的威胁。卫星图像显示在布卡武以北约60公里处建立新的前线作战基地。南基伍省与北基伍省交界处紧张局势加剧。",source:"UCDP",sourceUrl:"https://ucdp.uu.se/",verified:true},
  {id:"DRC-020",date:"2026-04-10",country:"DR Congo",province:"South Kivu",city:"Uvira",lat:-3.370,lng:29.140,type:"battles",severity:"medium",fatalities:12,actor1:"Mai-Mai",actor2:"FARDC",title:"Mai-Mai民兵在南基伍省乌维拉地区与军方交火",desc:"地方Mai-Mai民兵在乌维拉地区袭击FARDC巡逻队，交火中双方各有伤亡。该地区多个Mai-Mai团体对政府驻军不满，认为其未能有效保护社区免受跨境袭击。",source:"ACLED",sourceUrl:"https://acleddata.com/",verified:true},
  {id:"DRC-021",date:"2026-03-20",country:"DR Congo",province:"South Kivu",city:"Fizi",lat:-4.300,lng:28.950,type:"violence-civilians",severity:"medium",fatalities:8,actor1:"FDLR",actor2:"平民",title:"FDLR残部在南基伍省菲齐地区抢劫村庄",desc:"卢旺达解放民主力量(FDLR)残余人员在菲齐地区偏远村庄实施抢劫，与当地民众发生冲突致8人死亡。FDLR近年实力虽大幅削弱，但仍在偏远林区活动。",source:"GDELT",sourceUrl:"https://www.gdeltproject.org/",verified:false},
  // === 上韦莱省 Haut-Uele ===
  {id:"DRC-008",date:"2026-04-02",country:"DR Congo",province:"Upper Uele",city:"Doruma",lat:4.733,lng:27.733,type:"violence-civilians",severity:"high",fatalities:15,actor1:"LRA残部",actor2:"平民",title:"上韦莱省LRA残部袭击致15平民死亡",desc:"上帝抵抗军(LRA)残余力量在上韦莱省偏远地区袭击村庄，绑架12人（包括5名儿童）。乌干达军方配合FARDC部队展开搜剿。LRA虽已式微，但残余分子仍在该省与中非共和国边境流窜。",source:"ACLED",sourceUrl:"https://acleddata.com/",verified:true},
  // === 坦噶尼喀省 Tanganyika ===
  {id:"DRC-007",date:"2026-04-15",country:"DR Congo",province:"Tanganyika",city:"Kalemie",lat:-5.933,lng:29.194,type:"violence-civilians",severity:"medium",fatalities:12,actor1:"Mai-Mai",actor2:"平民",title:"Mai-Mai民兵在坦噶尼喀省抢劫村庄",desc:"多个Mai-Mai派系在坦噶尼喀省偏远村庄发动协同抢劫和袭击，目标为当地商人和农民。FARDC已派遣增援部队前往该地区。坦噶尼喀省长期以来是多个Mai-Mai团体的活动区域。",source:"ACLED",sourceUrl:"https://acleddata.com/",verified:true},
  // === 金沙萨 Kinshasa ===
  {id:"DRC-022",date:"2026-05-01",country:"DR Congo",province:"Kinshasa",city:"Kinshasa",lat:-4.325,lng:15.322,type:"strategic-dev",severity:"low",fatalities:0,actor1:"政府",actor2:"MONUSCO",title:"金沙萨当局要求加速MONUSCO撤军进程",desc:"刚果(金)政府在金沙萨再次要求联刚稳定团(MONUSCO)加速撤离进程，声称国家主权不容长期依赖外部安全力量。但东部安全形势恶化使得撤军时间表一再推迟。联合国秘书长呼吁负责任过渡。",source:"UN News",sourceUrl:"https://news.un.org/",verified:true},
  {id:"DRC-023",date:"2026-04-05",country:"DR Congo",province:"Kinshasa",city:"Kinshasa",lat:-4.325,lng:15.322,type:"civil-unrest",severity:"low",fatalities:0,actor1:"民众",actor2:"警方",title:"金沙萨民众抗议东部安全形势恶化",desc:"金沙萨数百名市民在议会大楼外和平集会，抗议东部省份持续恶化的安全形势和政府应对不力。抗议和平进行，无暴力事件发生。",source:"Reuters",sourceUrl:"https://www.reuters.com/",verified:true},
  // === 上洛马米省 Haut-Lomami ===
  {id:"DRC-024",date:"2026-03-10",country:"DR Congo",province:"Haut-Lomami",city:"Kamina",lat:-8.735,lng:24.998,type:"strategic-dev",severity:"low",fatalities:0,actor1:"FARDC",actor2:"N/A",title:"FARDC在卡米纳军事基地开展大规模集训",desc:"FARDC在上洛马米省卡米纳军事基地开展大规模新兵集训，旨在补充东部前线损失。南非和布隆迪军事教官参与训练。该基地是刚果(金)最大的军事训练设施之一。",source:"GDELT",sourceUrl:"https://www.gdeltproject.org/",verified:false},
  // === 上加丹加省 Haut-Katanga ===
  {id:"DRC-025",date:"2026-04-20",country:"DR Congo",province:"Haut-Katanga",city:"Lubumbashi",lat:-11.688,lng:27.480,type:"civil-unrest",severity:"low",fatalities:0,actor1:"矿工工会",actor2:"矿业公司",title:"上加丹加省矿工就安全条件举行罢工",desc:"上加丹加省卢本巴希矿区的矿工工会举行罢工，抗议矿井安全条件恶劣和薪资拖欠。该省是刚果钴和铜的主要产区，罢工影响了部分矿场运营。",source:"Reuters",sourceUrl:"https://www.reuters.com/",verified:true},
  // === 历史重大事件 ===
  {id:"DRC-009",date:"2025-11-20",country:"DR Congo",province:"North Kivu",city:"Sake",lat:-1.583,lng:29.100,type:"battles",severity:"critical",fatalities:120,actor1:"M23",actor2:"FARDC",title:"【历史】2025年11月—M23夺取萨凯镇",desc:"2025年11月，M23武装在北基伍省发动大规模攻势，经过一周激战后夺取战略要地萨凯镇，威胁戈马市。这是自2012-2013年M23上次叛乱以来最严重的军事升级。联合国安理会召开紧急会议。",source:"ACLED",sourceUrl:"https://acleddata.com/",verified:true},
  {id:"DRC-010",date:"2022-03-28",country:"DR Congo",province:"North Kivu",city:"Rutshuru",lat:-1.186,lng:29.449,type:"battles",severity:"high",fatalities:45,actor1:"M23",actor2:"FARDC",title:"【历史】2022年3月—M23重新活跃",desc:"2022年3月，沉寂近十年的M23反政府武装在北基伍省重新发动进攻，夺取布纳加纳(Bunagana)等多个边境城镇。刚果(金)政府指控卢旺达支持M23，卢旺达否认。联合国专家报告证实了卢旺达国防军的直接介入。",source:"ACLED",sourceUrl:"https://acleddata.com/",verified:true},
  {id:"DRC-026",date:"2021-05-06",country:"DR Congo",province:"North Kivu",city:"Goma",lat:-1.679,lng:29.233,type:"strategic-dev",severity:"medium",fatalities:0,actor1:"政府",actor2:"N/A",title:"【历史】2021年—刚果(金)宣布北基伍和伊图里省戒严",desc:"2021年5月，齐塞克迪总统宣布北基伍省和伊图里省进入戒严状态（état de siège），以应对日益恶化的安全局势。军政府取代了文官行政机构。五年后，戒严令的效果受到广泛质疑，两省安全形势持续恶化。",source:"ReliefWeb",sourceUrl:"https://reliefweb.int/",verified:true},
  {id:"DRC-027",date:"2020-02-15",country:"DR Congo",province:"Ituri",city:"Djugu",lat:1.733,lng:30.500,type:"violence-civilians",severity:"critical",fatalities:92,actor1:"CODECO",actor2:"平民",title:"【历史】2020年—伊图里省爆发大规模族群暴力",desc:"2020年初，伊图里省伦杜(Lendu)和赫马(Hema)族群之间的暴力冲突急剧升级，CODECO民兵对赫马族村庄发动一系列致命袭击。冲突根源可追溯至殖民时期，涉及土地权属和矿产资源控制等深层矛盾。",source:"ACLED",sourceUrl:"https://acleddata.com/",verified:true}
];
