/* =====================================================================
   DATA LAYER — 刚果(金)冲突事件（2010-2026）
   数据来源: ACLED (https://acleddata.com/) — 专家编码冲突数据
   覆盖: 2010-07 (MONUSCO成立) 至 2026-05 · 25/26省
   内联: 103条核心事件 · 脚本加载: incidents.js
   ===================================================================== */
var INCIDENTS = [
  {
    "id": "DRC-001",
    "date": "2026-05-25",
    "country": "DR Congo",
    "province": "North Kivu",
    "city": "Goma",
    "lat": -1.679,
    "lng": 29.233,
    "type": "battles",
    "severity": "critical",
    "fatalities": 89,
    "actor1": "M23",
    "actor2": "FARDC",
    "title": "M23武装在戈马以北发动大规模攻势",
    "desc": "M23反政府武装在北基伍省戈马以北地区发动协同攻势，使用重武器和无人机。FARDC在联刚稳定团支援下组织防御。联合国报告称新一轮冲突导致超过15万平民流离失所，人道主义形势严峻。",
    "source": "ACLED",
    "sourceUrl": "https://acleddata.com/",
    "verified": true
  },
  {
    "id": "DRC-015",
    "date": "2026-05-22",
    "country": "DR Congo",
    "province": "North Kivu",
    "city": "Sake",
    "lat": -1.583,
    "lng": 29.1,
    "type": "battles",
    "severity": "critical",
    "fatalities": 67,
    "actor1": "M23",
    "actor2": "FARDC",
    "title": "M23占领萨凯镇东部阵地，逼近戈马市",
    "desc": "M23在北基伍省萨凯镇附近突破FARDC防线，占领多个战略高地，距离戈马市仅25公里。Wazalendo民兵协助FARDC建立新防线。戈马市居民大规模恐慌撤离。",
    "source": "ACLED",
    "sourceUrl": "https://acleddata.com/",
    "verified": true
  },
  {
    "id": "DRC-002",
    "date": "2026-05-20",
    "country": "DR Congo",
    "province": "Ituri",
    "city": "Bunia",
    "lat": 1.565,
    "lng": 30.252,
    "type": "violence-civilians",
    "severity": "critical",
    "fatalities": 47,
    "actor1": "CODECO",
    "actor2": "平民",
    "title": "CODECO武装在伊图里省袭击村庄致47死",
    "desc": "CODECO民兵在伊图里省朱古地区多个村庄发动协同袭击，主要针对赫马族平民。袭击者使用砍刀和轻武器，焚烧超过200间房屋。该事件是伊图里省2026年以来最严重的族群暴力事件。",
    "source": "ACLED",
    "sourceUrl": "https://acleddata.com/",
    "verified": true
  },
  {
    "id": "DRC-003",
    "date": "2026-05-18",
    "country": "DR Congo",
    "province": "North Kivu",
    "city": "Beni",
    "lat": 0.491,
    "lng": 29.473,
    "type": "remote-violence",
    "severity": "high",
    "fatalities": 23,
    "actor1": "ADF",
    "actor2": "平民",
    "title": "ADF在北基伍省贝尼地区发动爆炸袭击",
    "desc": "民主同盟军(ADF)在贝尼地区一个市场附近引爆两枚IED，并随后开枪射击逃离人群。袭击造成至少23名平民死亡，30余人受伤。ADF已宣誓效忠伊斯兰国(ISCAP)。",
    "source": "ACLED",
    "sourceUrl": "https://acleddata.com/",
    "verified": true
  },
  {
    "id": "DRC-016",
    "date": "2026-05-15",
    "country": "DR Congo",
    "province": "North Kivu",
    "city": "Masisi",
    "lat": -1.402,
    "lng": 28.815,
    "type": "violence-civilians",
    "severity": "high",
    "fatalities": 34,
    "actor1": "M23",
    "actor2": "平民",
    "title": "M23控制区据报发生针对平民暴力事件",
    "desc": "联合国人权高专办收到报告称M23在马西西地区控制区对拒绝合作的平民实施暴力。具体细节正在核实中。M23否认相关指控。",
    "source": "UN News",
    "sourceUrl": "https://news.un.org/",
    "verified": false
  },
  {
    "id": "DRC-004",
    "date": "2026-05-15",
    "country": "DR Congo",
    "province": "South Kivu",
    "city": "Bukavu",
    "lat": -2.508,
    "lng": 28.861,
    "type": "strategic-dev",
    "severity": "medium",
    "fatalities": 0,
    "actor1": "FARDC",
    "actor2": "M23",
    "title": "刚果(金)政府军在南基伍省大规模增兵",
    "desc": "刚果(金)武装部队向南基伍省部署额外三个营的兵力，以应对M23向南扩张的威胁。卫星图像显示在布卡武以北约60公里处建立新的前线作战基地。南基伍省与北基伍省交界处紧张局势加剧。",
    "source": "UCDP",
    "sourceUrl": "https://ucdp.uu.se/",
    "verified": true
  },
  {
    "id": "DRC-005",
    "date": "2026-05-10",
    "country": "DR Congo",
    "province": "North Kivu",
    "city": "Rutshuru",
    "lat": -1.186,
    "lng": 29.449,
    "type": "battles",
    "severity": "high",
    "fatalities": 34,
    "actor1": "FARDC",
    "actor2": "M23",
    "title": "FARDC与M23在鲁丘鲁地区激战",
    "desc": "刚果(金)武装部队在联刚稳定团火力支援下对M23控制的鲁丘鲁地区发起反攻。双方在多个村庄展开拉锯战，FARDC声称收复两个村庄，但M23否认。",
    "source": "ACLED",
    "sourceUrl": "https://acleddata.com/",
    "verified": true
  },
  {
    "id": "DRC-017",
    "date": "2026-05-08",
    "country": "DR Congo",
    "province": "North Kivu",
    "city": "Butembo",
    "lat": 0.126,
    "lng": 29.289,
    "type": "remote-violence",
    "severity": "medium",
    "fatalities": 11,
    "actor1": "ADF",
    "actor2": "平民",
    "title": "ADF在布滕博郊区发动伏击",
    "desc": "ADF武装分子在布滕博市郊区伏击了一辆民用巴士，造成11名乘客死亡。当地民间社会呼吁政府加强该地区的安全措施。",
    "source": "ACLED",
    "sourceUrl": "https://acleddata.com/",
    "verified": true
  },
  {
    "id": "DRC-022",
    "date": "2026-05-01",
    "country": "DR Congo",
    "province": "Kinshasa",
    "city": "Kinshasa",
    "lat": -4.325,
    "lng": 15.322,
    "type": "strategic-dev",
    "severity": "low",
    "fatalities": 0,
    "actor1": "政府",
    "actor2": "MONUSCO",
    "title": "金沙萨当局要求加速MONUSCO撤军进程",
    "desc": "刚果(金)政府在金沙萨再次要求联刚稳定团(MONUSCO)加速撤离进程，声称国家主权不容长期依赖外部安全力量。但东部安全形势恶化使得撤军时间表一再推迟。联合国秘书长呼吁负责任过渡。",
    "source": "UN News",
    "sourceUrl": "https://news.un.org/",
    "verified": true
  },
  {
    "id": "DRC-006",
    "date": "2026-04-28",
    "country": "DR Congo",
    "province": "Ituri",
    "city": "Djugu",
    "lat": 1.733,
    "lng": 30.5,
    "type": "battles",
    "severity": "high",
    "fatalities": 28,
    "actor1": "Zaire Militia",
    "actor2": "CODECO",
    "title": "扎伊尔民兵与CODECO在伊图里省交火",
    "desc": "亲赫马族的扎伊尔民兵与伦杜族为主的CODECO武装在朱古地区发生冲突，双方使用迫击炮和重机枪。此次冲突是伊图里族群紧张的最新升级，约12,000名平民逃离冲突区域。",
    "source": "ACLED",
    "sourceUrl": "https://acleddata.com/",
    "verified": true
  },
  {
    "id": "DRC-025",
    "date": "2026-04-20",
    "country": "DR Congo",
    "province": "Haut-Katanga",
    "city": "Lubumbashi",
    "lat": -11.688,
    "lng": 27.48,
    "type": "strategic-dev",
    "severity": "low",
    "fatalities": 0,
    "actor1": "矿工工会",
    "actor2": "矿业公司",
    "title": "上加丹加省矿工就安全条件举行罢工",
    "desc": "上加丹加省卢本巴希矿区的矿工工会举行罢工，抗议矿井安全条件恶劣和薪资拖欠。该省是刚果钴和铜的主要产区，罢工影响了部分矿场运营。",
    "source": "Reuters",
    "sourceUrl": "https://www.reuters.com/",
    "verified": true
  },
  {
    "id": "DRC-018",
    "date": "2026-04-15",
    "country": "DR Congo",
    "province": "Ituri",
    "city": "Irumu",
    "lat": 1.45,
    "lng": 29.85,
    "type": "violence-civilians",
    "severity": "medium",
    "fatalities": 14,
    "actor1": "ADF",
    "actor2": "平民",
    "title": "ADF在伊鲁穆地区绑架平民",
    "desc": "ADF武装在伊鲁穆地区袭击了一个村庄，绑架14名平民并焚烧多处房屋。当地村民报告称ADF近期活动频率显著增加。",
    "source": "ACLED",
    "sourceUrl": "https://acleddata.com/",
    "verified": true
  },
  {
    "id": "DRC-007",
    "date": "2026-04-15",
    "country": "DR Congo",
    "province": "Tanganyika",
    "city": "Kalemie",
    "lat": -5.933,
    "lng": 29.194,
    "type": "violence-civilians",
    "severity": "medium",
    "fatalities": 12,
    "actor1": "Mai-Mai",
    "actor2": "平民",
    "title": "Mai-Mai民兵在坦噶尼喀省抢劫村庄",
    "desc": "多个Mai-Mai派系在坦噶尼喀省偏远村庄发动协同抢劫和袭击，目标为当地商人和农民。FARDC已派遣增援部队前往该地区。坦噶尼喀省长期以来是多个Mai-Mai团体的活动区域。",
    "source": "ACLED",
    "sourceUrl": "https://acleddata.com/",
    "verified": true
  },
  {
    "id": "DRC-020",
    "date": "2026-04-10",
    "country": "DR Congo",
    "province": "South Kivu",
    "city": "Uvira",
    "lat": -3.37,
    "lng": 29.14,
    "type": "battles",
    "severity": "medium",
    "fatalities": 12,
    "actor1": "Mai-Mai",
    "actor2": "FARDC",
    "title": "Mai-Mai民兵在南基伍省乌维拉地区与军方交火",
    "desc": "地方Mai-Mai民兵在乌维拉地区袭击FARDC巡逻队，交火中双方各有伤亡。该地区多个Mai-Mai团体对政府驻军不满，认为其未能有效保护社区免受跨境袭击。",
    "source": "ACLED",
    "sourceUrl": "https://acleddata.com/",
    "verified": true
  },
  {
    "id": "DRC-023",
    "date": "2026-04-05",
    "country": "DR Congo",
    "province": "Kinshasa",
    "city": "Kinshasa",
    "lat": -4.325,
    "lng": 15.322,
    "type": "strategic-dev",
    "severity": "low",
    "fatalities": 0,
    "actor1": "民众",
    "actor2": "警方",
    "title": "金沙萨民众抗议东部安全形势恶化",
    "desc": "金沙萨数百名市民在议会大楼外和平集会，抗议东部省份持续恶化的安全形势和政府应对不力。抗议和平进行，无暴力事件发生。",
    "source": "Reuters",
    "sourceUrl": "https://www.reuters.com/",
    "verified": true
  },
  {
    "id": "DRC-008",
    "date": "2026-04-02",
    "country": "DR Congo",
    "province": "Upper Uele",
    "city": "Doruma",
    "lat": 4.733,
    "lng": 27.733,
    "type": "violence-civilians",
    "severity": "high",
    "fatalities": 15,
    "actor1": "LRA残部",
    "actor2": "平民",
    "title": "上韦莱省LRA残部袭击致15平民死亡",
    "desc": "上帝抵抗军(LRA)残余力量在上韦莱省偏远地区袭击村庄，绑架12人（包括5名儿童）。乌干达军方配合FARDC部队展开搜剿。LRA虽已式微，但残余分子仍在该省与中非共和国边境流窜。",
    "source": "ACLED",
    "sourceUrl": "https://acleddata.com/",
    "verified": true
  },
  {
    "id": "DRC-019",
    "date": "2026-03-25",
    "country": "DR Congo",
    "province": "Ituri",
    "city": "Mahagi",
    "lat": 2.3,
    "lng": 31.0,
    "type": "battles",
    "severity": "medium",
    "fatalities": 19,
    "actor1": "CODECO",
    "actor2": "FARDC",
    "title": "CODECO攻击伊图里省北部军事哨所",
    "desc": "CODECO派系在马哈吉地区对FARDC军事哨所发动攻击，双方交火约3小时。FARDC最终击退进攻，但付出了伤亡代价。",
    "source": "GDELT",
    "sourceUrl": "https://www.gdeltproject.org/",
    "verified": true
  },
  {
    "id": "DRC-021",
    "date": "2026-03-20",
    "country": "DR Congo",
    "province": "South Kivu",
    "city": "Fizi",
    "lat": -4.3,
    "lng": 28.95,
    "type": "violence-civilians",
    "severity": "medium",
    "fatalities": 8,
    "actor1": "FDLR",
    "actor2": "平民",
    "title": "FDLR残部在南基伍省菲齐地区抢劫村庄",
    "desc": "卢旺达解放民主力量(FDLR)残余人员在菲齐地区偏远村庄实施抢劫，与当地民众发生冲突致8人死亡。FDLR近年实力虽大幅削弱，但仍在偏远林区活动。",
    "source": "GDELT",
    "sourceUrl": "https://www.gdeltproject.org/",
    "verified": false
  },
  {
    "id": "DRC-024",
    "date": "2026-03-10",
    "country": "DR Congo",
    "province": "Haut-Lomami",
    "city": "Kamina",
    "lat": -8.735,
    "lng": 24.998,
    "type": "strategic-dev",
    "severity": "low",
    "fatalities": 0,
    "actor1": "FARDC",
    "actor2": "N/A",
    "title": "FARDC在卡米纳军事基地开展大规模集训",
    "desc": "FARDC在上洛马米省卡米纳军事基地开展大规模新兵集训，旨在补充东部前线损失。南非和布隆迪军事教官参与训练。该基地是刚果(金)最大的军事训练设施之一。",
    "source": "GDELT",
    "sourceUrl": "https://www.gdeltproject.org/",
    "verified": false
  },
  {
    "id": "DRC-009",
    "date": "2025-11-20",
    "country": "DR Congo",
    "province": "North Kivu",
    "city": "Sake",
    "lat": -1.583,
    "lng": 29.1,
    "type": "battles",
    "severity": "critical",
    "fatalities": 120,
    "actor1": "M23",
    "actor2": "FARDC",
    "title": "【历史】2025年11月—M23夺取萨凯镇",
    "desc": "2025年11月，M23武装在北基伍省发动大规模攻势，经过一周激战后夺取战略要地萨凯镇，威胁戈马市。这是自2012-2013年M23上次叛乱以来最严重的军事升级。联合国安理会召开紧急会议。",
    "source": "ACLED",
    "sourceUrl": "https://acleddata.com/",
    "verified": true
  },
  {
    "id": "ACLED-FF2427095B",
    "date": "2025-02-13",
    "country": "DR Congo",
    "province": "North Kivu",
    "city": "Vuyinga",
    "lat": 0.0607,
    "lng": 29.0509,
    "type": "violence-civilians",
    "severity": "critical",
    "fatalities": 70,
    "actor1": "Unidentified Armed Group (Democratic Republic of Congo)",
    "actor2": "Civilians (Democratic Republic of Congo)",
    "title": "Around 13 February 2025 (between 11 - 14 February), unidentified individuals (reports differ on group involvement, mentioning ADF, UPLC or FPP/AP) kil",
    "desc": "Around 13 February 2025 (between 11 - 14 February), unidentified individuals (reports differ on group involvement, mentioning ADF, UPLC or FPP/AP) killed at ; east 70 people and left their bodies at a protestant church building in Kasanga, coded to a nearby location, Vuyinga (Baswaga, Lubero, Nord-Kivu). The group had been abducted on the 11 February in Maibe (coded separately) (来源: ACLED, 事件ID: DRC43068)",
    "source": "ACLED",
    "sourceUrl": "https://acleddata.com/data/",
    "verified": true
  },
  {
    "id": "ACLED-41821EA3F8",
    "date": "2025-02-11",
    "country": "DR Congo",
    "province": "Ituri",
    "city": "Djaiba",
    "lat": 1.9853,
    "lng": 30.6041,
    "type": "violence-civilians",
    "severity": "critical",
    "fatalities": 80,
    "actor1": "CODECO: Cooperative for Development of Congo",
    "actor2": "Civilians (Democratic Republic of Congo)",
    "title": "On 11 February 2025, overnight, CODECO attacked civilians in Lodja village and other Hema villages, near Djaiba IDP camp in Djaiba groupement (Walendu",
    "desc": "On 11 February 2025, overnight, CODECO attacked civilians in Lodja village and other Hema villages, near Djaiba IDP camp in Djaiba groupement (Walendu-Djatsi, Djugu, Ituri), killing more than 80 people (final death toll). They also set 50 houses on fire. This attack was in reprisal for an earlier attack on Lendu civilians on 9 February (coded separately). Residents of Lodja and neighboring villages fled. (来源: ACLED, 事件ID: DRC34738)",
    "source": "ACLED",
    "sourceUrl": "https://acleddata.com/data/",
    "verified": true
  },
  {
    "id": "ACLED-228845756D",
    "date": "2025-01-29",
    "country": "DR Congo",
    "province": "North Kivu",
    "city": "Goma - Katoyi",
    "lat": -1.6459,
    "lng": 29.2016,
    "type": "battles",
    "severity": "critical",
    "fatalities": 59,
    "actor1": "M23: March 23 Movement",
    "actor2": "Military Forces of the Democratic Republic of Congo (2019-)",
    "title": "On 29 January 2025, M23-RDF clashed against FARDC-Wazalendo with heavy weapons in Goma - Katoyi (Karisimbi, Goma, Nord-Kivu), Majengo, Kasika and Turu",
    "desc": "On 29 January 2025, M23-RDF clashed against FARDC-Wazalendo with heavy weapons in Goma - Katoyi (Karisimbi, Goma, Nord-Kivu), Majengo, Kasika and Turunga, Mabanga, Kibwe districts (coded separately). From 26-31 January 2025 as per Congolese government numbers there were 1308 people injured and 412 killed as a result of M23 clashes in Karisimbi chiefdom. 412 fatalities split across seven applicable events as follows: Goma - Katoyi (59), Goma - Kasika (59), Goma - Bujovu (59), Goma - Mugunga (59), Goma - Majengo (118) (27 January (59) and 29 January (59)), Goma - Virunga (58). (来源: ACLED, 事件ID: DRC34548)",
    "source": "ACLED",
    "sourceUrl": "https://acleddata.com/data/",
    "verified": true
  },
  {
    "id": "ACLED-224B8AE540",
    "date": "2025-01-26",
    "country": "DR Congo",
    "province": "North Kivu",
    "city": "Sake",
    "lat": -1.5713,
    "lng": 29.0536,
    "type": "battles",
    "severity": "critical",
    "fatalities": 66,
    "actor1": "M23: March 23 Movement",
    "actor2": "Military Forces of the Democratic Republic of Congo (2019-)",
    "title": "On 26 January 2025, for the third of three consecutive days, M23-RDF clashed against FARDC in Sake (Masisi, Nord-Kivu), using heavy and light weapons.",
    "desc": "On 26 January 2025, for the third of three consecutive days, M23-RDF clashed against FARDC in Sake (Masisi, Nord-Kivu), using heavy and light weapons. At least 200 RDF were killed. At least 200 RDF fatalities split over three days as follows: 68 (24-01); 66 (25/01); 66 (26/01). (来源: ACLED, 事件ID: DRC39123)",
    "source": "ACLED",
    "sourceUrl": "https://acleddata.com/data/",
    "verified": true
  },
  {
    "id": "ACLED-3BF93B06B9",
    "date": "2025-01-25",
    "country": "DR Congo",
    "province": "North Kivu",
    "city": "Sake",
    "lat": -1.5713,
    "lng": 29.0536,
    "type": "battles",
    "severity": "critical",
    "fatalities": 66,
    "actor1": "M23: March 23 Movement",
    "actor2": "Military Forces of the Democratic Republic of Congo (2019-)",
    "title": "On 25 January 2025, for the second of three consecutive days, M23-RDF clashed against FARDC on the Sake-Goma road axis, coded to Sake (Masisi, Nord-Ki",
    "desc": "On 25 January 2025, for the second of three consecutive days, M23-RDF clashed against FARDC on the Sake-Goma road axis, coded to Sake (Masisi, Nord-Kivu), using heavy and light weapons. A movement of displaced persons, especially in the southern part of Nyiragongo has been observed towards Goma and Rutshuru. At least 200 RDF fatalities split over three days as follows: 68 (24-01); 66 (25/01); 66 (26/01). (来源: ACLED, 事件ID: DRC34597)",
    "source": "ACLED",
    "sourceUrl": "https://acleddata.com/data/",
    "verified": true
  },
  {
    "id": "ACLED-E2908182B1",
    "date": "2024-12-25",
    "country": "DR Congo",
    "province": "North Kivu",
    "city": "Beni",
    "lat": 0.4966,
    "lng": 29.4654,
    "type": "violence-civilians",
    "severity": "critical",
    "fatalities": 75,
    "actor1": "ADFL: Alliance of Democratic Forces for Liberation",
    "actor2": "Civilians (Democratic Republic of Congo)",
    "title": "Around 25 December 2024 (as reported), ADF attacked and killed at least 224 civilians in Beni (Beni, Nord-Kivu). Fatalities split across three events,",
    "desc": "Around 25 December 2024 (as reported), ADF attacked and killed at least 224 civilians in Beni (Beni, Nord-Kivu). Fatalities split across three events, coded as 75 for this event. (来源: ACLED, 事件ID: DRC38289)",
    "source": "ACLED",
    "sourceUrl": "https://acleddata.com/data/",
    "verified": true
  },
  {
    "id": "ACLED-F58928D7A7",
    "date": "2024-12-25",
    "country": "DR Congo",
    "province": "North Kivu",
    "city": "Butembo",
    "lat": 0.142,
    "lng": 29.291,
    "type": "violence-civilians",
    "severity": "critical",
    "fatalities": 75,
    "actor1": "ADFL: Alliance of Democratic Forces for Liberation",
    "actor2": "Civilians (Democratic Republic of Congo)",
    "title": "Around 25 December 2024 (as reported), ADF attacked and killed at least 224 civilians near Butembo (Butembo, Nord-Kivu). Fatalities split across three",
    "desc": "Around 25 December 2024 (as reported), ADF attacked and killed at least 224 civilians near Butembo (Butembo, Nord-Kivu). Fatalities split across three events, coded as 75 for this event. (来源: ACLED, 事件ID: DRC38290)",
    "source": "ACLED",
    "sourceUrl": "https://acleddata.com/data/",
    "verified": true
  },
  {
    "id": "ACLED-4E64E5923F",
    "date": "2024-12-25",
    "country": "DR Congo",
    "province": "North Kivu",
    "city": "Lubero",
    "lat": -0.1587,
    "lng": 29.2386,
    "type": "violence-civilians",
    "severity": "critical",
    "fatalities": 74,
    "actor1": "ADFL: Alliance of Democratic Forces for Liberation",
    "actor2": "Civilians (Democratic Republic of Congo)",
    "title": "Around 25 December 2024 (as reported), ADF attacked and killed at least 224 civilians in Lubero (Lubero, Nord-Kivu). Fatalities split across three eve",
    "desc": "Around 25 December 2024 (as reported), ADF attacked and killed at least 224 civilians in Lubero (Lubero, Nord-Kivu). Fatalities split across three events, coded as 74 for this event. (来源: ACLED, 事件ID: DRC38288)",
    "source": "ACLED",
    "sourceUrl": "https://acleddata.com/data/",
    "verified": true
  },
  {
    "id": "ACLED-2ACC753B96",
    "date": "2024-09-02",
    "country": "DR Congo",
    "province": "Kinshasa",
    "city": "Kinshasa",
    "lat": -4.325,
    "lng": 15.3222,
    "type": "strategic-dev",
    "severity": "critical",
    "fatalities": 409,
    "actor1": "Rioters (Democratic Republic of Congo)",
    "actor2": "Police Forces of the Democratic Republic of Congo (2019-)",
    "title": "On 2 September 2024, police and FARDC killed 406 prisoners and injured 200 others who were trying to escape during a prison break at the Makala prison",
    "desc": "On 2 September 2024, police and FARDC killed 406 prisoners and injured 200 others who were trying to escape during a prison break at the Makala prison in Kinshasa (Kinshasa). Prisoners were killed by bullets and by suffocation. 269 women were raped by other prisoners inside the prison. 3 women died shortly after the rapes. 409 fatalities. (来源: ACLED, 事件ID: DRC43207)",
    "source": "ACLED",
    "sourceUrl": "https://acleddata.com/data/",
    "verified": true
  },
  {
    "id": "ACLED-1524AD183A",
    "date": "2024-09-01",
    "country": "DR Congo",
    "province": "Kinshasa",
    "city": "Kinshasa - Selembao",
    "lat": -4.3764,
    "lng": 15.2964,
    "type": "strategic-dev",
    "severity": "critical",
    "fatalities": 200,
    "actor1": "Rioters (Democratic Republic of Congo)",
    "actor2": "Police Forces of the Democratic Republic of Congo (2019-) Prison Guards",
    "title": "On 1 September 2024, police violently repressed a prison break attempt at Makala prison, located between the commune of Makala and Selembao in Kinshas",
    "desc": "On 1 September 2024, police violently repressed a prison break attempt at Makala prison, located between the commune of Makala and Selembao in Kinshasa, coded to Kinshasa - Selembao (Kinshasa). Makala is the DRC's largest prison. A fire broke out during or before the riot, destroying the prison's facilities. At least 200 people died (according to recent reports as of 2024-11-29) as a result of a confrontation with security forces, At least 59 prisoners were injured and 268 women sexually assaulted. (来源: ACLED, 事件ID: DRC33491)",
    "source": "ACLED",
    "sourceUrl": "https://acleddata.com/data/",
    "verified": true
  },
  {
    "id": "ACLED-1A8D4894F6",
    "date": "2023-10-02",
    "country": "DR Congo",
    "province": "North Kivu",
    "city": "Goma",
    "lat": -1.6566,
    "lng": 29.2085,
    "type": "violence-civilians",
    "severity": "critical",
    "fatalities": 50,
    "actor1": "Military Forces of the Democratic Republic of Congo (2019-) Republican Guard",
    "actor2": "Civilians (Democratic Republic of Congo)",
    "title": "Around 2 October 2023, the Republican Guard and the police forces attacked civilians in Goma (Goma, Goma, Nord-Kivu). More than 50 civilians were kill",
    "desc": "Around 2 October 2023, the Republican Guard and the police forces attacked civilians in Goma (Goma, Goma, Nord-Kivu). More than 50 civilians were killed. (来源: ACLED, 事件ID: DRC30799)",
    "source": "ACLED",
    "sourceUrl": "https://acleddata.com/data/",
    "verified": true
  },
  {
    "id": "ACLED-4CC0F1A6A3",
    "date": "2023-08-30",
    "country": "DR Congo",
    "province": "North Kivu",
    "city": "Goma",
    "lat": -1.6566,
    "lng": 29.2085,
    "type": "strategic-dev",
    "severity": "critical",
    "fatalities": 51,
    "actor1": "Protesters (Democratic Republic of Congo)",
    "actor2": "Military Forces of the Democratic Republic of Congo (2019-)",
    "title": "On 30 August 2023, 51 - 108 people were killed as FARDC, including the Republican Guard, and the Police attempted to scatter a protest called out by t",
    "desc": "On 30 August 2023, 51 - 108 people were killed as FARDC, including the Republican Guard, and the Police attempted to scatter a protest called out by the Guru of FNJMN sect, who claims to be Wazalendo-affiliated, in Goma (Goma, Nord-Kivu) to demand the departure of MONUSCO. 6 civilians were killed at the premises of the radio of the sect called Uwezo Wa Neno including a journalist and people invited to her radio program. Furthermore, a police officer was lynched by the protesters and FARDC set ablaze the church of the sect. (来源: ACLED, 事件ID: DRC30424)",
    "source": "ACLED",
    "sourceUrl": "https://acleddata.com/data/",
    "verified": true
  },
  {
    "id": "ACLED-F5F3703D09",
    "date": "2023-06-12",
    "country": "DR Congo",
    "province": "Ituri",
    "city": "Bule",
    "lat": 1.9167,
    "lng": 30.6,
    "type": "violence-civilians",
    "severity": "critical",
    "fatalities": 46,
    "actor1": "CODECO: Cooperative for Development of Congo",
    "actor2": "Civilians (Democratic Republic of Congo)",
    "title": "On 12 June 2023, CODECO militiamen attacked an IDP camp hosting mostly Hema displaced people, located in Lala, in the Bahema-Badjere chiefdom, 4km awa",
    "desc": "On 12 June 2023, CODECO militiamen attacked an IDP camp hosting mostly Hema displaced people, located in Lala, in the Bahema-Badjere chiefdom, 4km away from Bule (Djugu, Ituri). At least 46 civilians (including 23 minors (25 according to the Congolese authorities) and at least 13 women) were killed. Some were shot dead, some were hacked to death and others were burned alive in their homes. About a dozen civilians were left with serious injuries. Houses were burnt down (according to UNICEF 800 shelters were set on fire) and property and livestock were looted. FARDC and MONUSCO deployed in the nearby town of Bule failed to intervene, even though civilians alerted them while the attack was unfolding. A MONUSCO officer said they did not intervene as one of their armored personnel carriers broke down. The Governor of Ituri claimed armed men were hiding in the camp amongst the IDPs. An investigation was opened and two CODECO leaders were issued arrest warrants by the FARDC. The Ituri Governor claimed that the attack was planned during a meeting held in Dala during which FARDC military outfits were handed over to the militiamen. 14 people suspected to be involved in the attack were arrested on 16 June 2023. (来源: ACLED, 事件ID: DRC29855)",
    "source": "ACLED",
    "sourceUrl": "https://acleddata.com/data/",
    "verified": true
  },
  {
    "id": "ACLED-8FFE73E4C2",
    "date": "2023-04-22",
    "country": "DR Congo",
    "province": "North Kivu",
    "city": "Kashali",
    "lat": -1.2506,
    "lng": 29.1124,
    "type": "violence-civilians",
    "severity": "critical",
    "fatalities": 60,
    "actor1": "M23: March 23 Movement",
    "actor2": "Civilians (Democratic Republic of Congo)",
    "title": "Around 22 April 2023 (between 20 April - 25 April), according to government officials, M23 killed 'at least' 60 civilians 'near' Kashali and Kazaroho ",
    "desc": "Around 22 April 2023 (between 20 April - 25 April), according to government officials, M23 killed 'at least' 60 civilians 'near' Kashali and Kazaroho villages, coded to Kashali (Bwito, Rutshuru, Nord-Kivu). M23 denied allegations and accused FDLR. (来源: ACLED, 事件ID: DRC29548)",
    "source": "ACLED",
    "sourceUrl": "https://acleddata.com/data/",
    "verified": true
  },
  {
    "id": "ACLED-F1DBAD01E8",
    "date": "2023-04-12",
    "country": "DR Congo",
    "province": "Ituri",
    "city": "Lisey",
    "lat": 1.7515,
    "lng": 30.0829,
    "type": "battles",
    "severity": "critical",
    "fatalities": 47,
    "actor1": "CODECO: Cooperative for Development of Congo",
    "actor2": "FPAC: Ituri Self-Defense Popular Front (Zaire)",
    "title": "Around 12 April 2023, CODECO clashed against Zaire in Lisey (Banyali-Kilo, Djugu, Ituri). 43 CODECO and 4 Zaire dead.",
    "desc": "Around 12 April 2023, CODECO clashed against Zaire in Lisey (Banyali-Kilo, Djugu, Ituri). 43 CODECO and 4 Zaire dead. (来源: ACLED, 事件ID: DRC29387)",
    "source": "ACLED",
    "sourceUrl": "https://acleddata.com/data/",
    "verified": true
  },
  {
    "id": "ACLED-6415C8DB2D",
    "date": "2022-11-29",
    "country": "DR Congo",
    "province": "North Kivu",
    "city": "Kishishi",
    "lat": -1.0025,
    "lng": 29.2026,
    "type": "battles",
    "severity": "critical",
    "fatalities": 131,
    "actor1": "M23: March 23 Movement",
    "actor2": "FDLR: Democratic Forces for the Liberation of Rwanda",
    "title": "On 29 November 2022, M23 clashed with FDLR and a coalition of Mayi Mayi including Nyatura (Hutu Based), CMC and Mazembe in Kishishi (also spelt as Kis",
    "desc": "On 29 November 2022, M23 clashed with FDLR and a coalition of Mayi Mayi including Nyatura (Hutu Based), CMC and Mazembe in Kishishi (also spelt as Kishishe) - and surrounding locations such as Bambo, Bunyama, Kilama, and Kongakonga - a locality of Bambu groupement (Bwito, Rutshuru, Nord-Kivu). M23 regained control of Kishishe, lost a few days earlier (coded separately). During and after the clashes, 131-272 civilians were killed, including IDPs and children, by the M23 over suspicion of alliance with the Mayi Mayi. A local dignitary said 64 victims had taken refuge in a church and all men had been shot whilst women were released. 20 men, mostly young, were abducted by the group and brought to their position in Rubare. The DRC government, who claimed 272 civilians were killed, including at least 17 children, called for an international investigation for war crimes. M23, who called for an 'independent inquiry', rejected the allegations and instead claimed that 21 Mayi Mayi were killed during the clashes and 8 civilians were killed by stray bullets. An investigation was opened by the Attorney General. The UN deployed a preliminary investigation which concluded on 8 December 2022 in at least 131 civilians killed by bullets and bladed weapons between 29 and 30 November 2022. The report also mentioned the nearby Bambu village as having been affected with 60 civilians abducted and 22 women and 5 girls raped. The M23 rejected the conclusions of the UN investigation claiming it was not impartial. Likewise, on 21 December 2022, the Rwandese Government accused DRC of having 'fabricated' conclusions without a serious entity conducting investigations on the events in order to put the blame on the M23. In February 2023, Human Rights Watch said they were able to verify the identity of 22 civilians killed. Also in February 2023, Amnesty International said M23 had killed at least 20 civilians, and raped 66 women and girls in the area from 21-30 November (some specific instances coded). M23 rejected the sexual violence accusations. Civilians fled towards Kibirizi. Witnesses mentioned they saw mass graves and some victims recounted they had to bury themselves victims. On 14 June 2023, HRW reported on the presence of 14 mass graves in Kishishe (coded separately). (来源: ACLED, 事件ID: DRC27624)",
    "source": "ACLED",
    "sourceUrl": "https://acleddata.com/data/",
    "verified": true
  },
  {
    "id": "ACLED-A0C74CD904",
    "date": "2022-09-23",
    "country": "DR Congo",
    "province": "Mai-Ndombe",
    "city": "Bishala",
    "lat": -3.7506,
    "lng": 17.1616,
    "type": "violence-civilians",
    "severity": "critical",
    "fatalities": 90,
    "actor1": "Unidentified Communal Militia (Democratic Republic of Congo)",
    "actor2": "Civilians (Democratic Republic of Congo)",
    "title": "On 23 September 2022, an unidentified communal militia armed with machetes, arrows, and guns killed about 90 people, including several teachers and st",
    "desc": "On 23 September 2022, an unidentified communal militia armed with machetes, arrows, and guns killed about 90 people, including several teachers and students, in the village of Bishala (Plateaux, Kwamouth, Mai-Ndombe), in the context of intercommunal conflicts. (来源: ACLED, 事件ID: DRC26963)",
    "source": "ACLED",
    "sourceUrl": "https://acleddata.com/data/",
    "verified": true
  },
  {
    "id": "ACLED-1808ABDC5F",
    "date": "2022-09-20",
    "country": "DR Congo",
    "province": "Mai-Ndombe",
    "city": "Kwamouth",
    "lat": -3.182,
    "lng": 16.2044,
    "type": "battles",
    "severity": "critical",
    "fatalities": 64,
    "actor1": "Teke Ethnic Militia (Democratic Republic of Congo)",
    "actor2": "Yaka Ethnic Militia (Democratic Republic of Congo)",
    "title": "On 20 September 2022, Teke and Yaka ethnic militias clashed against one another in Ingwene and Bisiala villages, Kwamouth territory, coded to territor",
    "desc": "On 20 September 2022, Teke and Yaka ethnic militias clashed against one another in Ingwene and Bisiala villages, Kwamouth territory, coded to territorial capital Kwamouth (Plateaux, Kwamouth, Mai-Ndombe). Fatality estimates range from 64 to 90, with 25 Teke (including the customary chief), 45 Yaka and 5 FARDC dead in Ingwene, and approximately 20 people killed in Bisiala. (来源: ACLED, 事件ID: DRC26938)",
    "source": "ACLED",
    "sourceUrl": "https://acleddata.com/data/",
    "verified": true
  },
  {
    "id": "ACLED-7911020880",
    "date": "2022-05-27",
    "country": "DR Congo",
    "province": "South Kivu",
    "city": "Kigoma",
    "lat": -2.9427,
    "lng": 28.9373,
    "type": "battles",
    "severity": "critical",
    "fatalities": 54,
    "actor1": "Military Forces of Burundi (2005-)",
    "actor2": "RED-TABARA: Resistance for the Rule of Law in Burundi",
    "title": "On 27 May 2022, FDNB, Imbonerakure and Gumino clashed with the RED-TABARA and the Mayi Mayi Ilunga in the villages of Lubumba, Kitoga and Rubuga aroun",
    "desc": "On 27 May 2022, FDNB, Imbonerakure and Gumino clashed with the RED-TABARA and the Mayi Mayi Ilunga in the villages of Lubumba, Kitoga and Rubuga around Kigoma (Uvira, Sud-Kivu), leaving 42 FDNB and their allies, and 12 RED-TABARA, dead. (来源: ACLED, 事件ID: DRC40812)",
    "source": "ACLED",
    "sourceUrl": "https://acleddata.com/data/",
    "verified": true
  },
  {
    "id": "DRC-010",
    "date": "2022-03-28",
    "country": "DR Congo",
    "province": "North Kivu",
    "city": "Rutshuru",
    "lat": -1.186,
    "lng": 29.449,
    "type": "battles",
    "severity": "high",
    "fatalities": 45,
    "actor1": "M23",
    "actor2": "FARDC",
    "title": "【历史】2022年3月—M23重新活跃",
    "desc": "2022年3月，沉寂近十年的M23反政府武装在北基伍省重新发动进攻，夺取布纳加纳(Bunagana)等多个边境城镇。刚果(金)政府指控卢旺达支持M23，卢旺达否认。联合国专家报告证实了卢旺达国防军的直接介入。",
    "source": "ACLED",
    "sourceUrl": "https://acleddata.com/",
    "verified": true
  },
  {
    "id": "ACLED-BAA9B117B0",
    "date": "2022-01-11",
    "country": "DR Congo",
    "province": "South Kivu",
    "city": "Uvira",
    "lat": -3.3953,
    "lng": 29.1378,
    "type": "violence-civilians",
    "severity": "critical",
    "fatalities": 67,
    "actor1": "Military Forces of Burundi (2005-)",
    "actor2": "Civilians (Democratic Republic of Congo)",
    "title": "Around 11 January 2022 (between 19 December - 3 February), the Burundi armed forces killed at least 67 civilians, set on fire 17 villages and looted c",
    "desc": "Around 11 January 2022 (between 19 December - 3 February), the Burundi armed forces killed at least 67 civilians, set on fire 17 villages and looted cows from pastoralists in Uvira territory (Sud-Kivu). (来源: ACLED, 事件ID: DRC24188)",
    "source": "ACLED",
    "sourceUrl": "https://acleddata.com/data/",
    "verified": true
  },
  {
    "id": "ACLED-E85BF0D0B3",
    "date": "2021-12-14",
    "country": "DR Congo",
    "province": "North Kivu",
    "city": "Kambi Ya Yua",
    "lat": 0.7896,
    "lng": 29.8123,
    "type": "battles",
    "severity": "critical",
    "fatalities": 100,
    "actor1": "Military Forces of the Democratic Republic of Congo (2019-)",
    "actor2": "ADF: Allied Democratic Forces",
    "title": "On 14 December 2021, the Congolese and Ugandan armies clashed with and bombarded the ADF in Batonga (known as Kambi Ya Yua) (Beni, Nord-Kivu) [some so",
    "desc": "On 14 December 2021, the Congolese and Ugandan armies clashed with and bombarded the ADF in Batonga (known as Kambi Ya Yua) (Beni, Nord-Kivu) [some sources locate it in Ituri province]. 3,000 militants fled the area. Some sources suggest over 200 casualties were incurred by the ADF. Subsequent reports suggest that over 100 ADF were killed, when mass graves were discovered around 30 January 2022 (coded as another event). The government seized the base. (来源: ACLED, 事件ID: DRC23694)",
    "source": "ACLED",
    "sourceUrl": "https://acleddata.com/data/",
    "verified": true
  },
  {
    "id": "ACLED-2448964F63",
    "date": "2021-07-25",
    "country": "DR Congo",
    "province": "Tanganyika",
    "city": "Kalemie",
    "lat": -5.937,
    "lng": 29.1785,
    "type": "violence-civilians",
    "severity": "critical",
    "fatalities": 46,
    "actor1": "Batwa Ethnic Militia (Democratic Republic of Congo)",
    "actor2": "Civilians (Democratic Republic of Congo)",
    "title": "Around 25 July 2021 (between 1 July - 18 August), Batwa militiamen reportedly killed 46 people, raped 16 women and wounded other people Tanganyika pro",
    "desc": "Around 25 July 2021 (between 1 July - 18 August), Batwa militiamen reportedly killed 46 people, raped 16 women and wounded other people Tanganyika province [coded as Kalemie] They also attacked more than 6 villages, triggered the displacement of more than 500 miners. (来源: ACLED, 事件ID: DRC22201)",
    "source": "ACLED",
    "sourceUrl": "https://acleddata.com/data/",
    "verified": true
  },
  {
    "id": "ACLED-BE55816DE0",
    "date": "2021-06-02",
    "country": "DR Congo",
    "province": "Ituri",
    "city": "Irumu",
    "lat": 1.4528,
    "lng": 29.8748,
    "type": "battles",
    "severity": "critical",
    "fatalities": 90,
    "actor1": "Military Forces of the Democratic Republic of Congo (2019-)",
    "actor2": "ADF: Allied Democratic Forces",
    "title": "Around 2 June 2021 (between 6 May - 29 June), the FARDC killed 90 ADF militants across the province of Ituri [coded as Irumu].",
    "desc": "Around 2 June 2021 (between 6 May - 29 June), the FARDC killed 90 ADF militants across the province of Ituri [coded as Irumu]. (来源: ACLED, 事件ID: DRC21693)",
    "source": "ACLED",
    "sourceUrl": "https://acleddata.com/data/",
    "verified": true
  },
  {
    "id": "DRC-026",
    "date": "2021-05-06",
    "country": "DR Congo",
    "province": "North Kivu",
    "city": "Goma",
    "lat": -1.679,
    "lng": 29.233,
    "type": "strategic-dev",
    "severity": "medium",
    "fatalities": 0,
    "actor1": "政府",
    "actor2": "N/A",
    "title": "【历史】2021年—刚果(金)宣布北基伍和伊图里省戒严",
    "desc": "2021年5月，齐塞克迪总统宣布北基伍省和伊图里省进入戒严状态（état de siège），以应对日益恶化的安全局势。军政府取代了文官行政机构。五年后，戒严令的效果受到广泛质疑，两省安全形势持续恶化。",
    "source": "ReliefWeb",
    "sourceUrl": "https://reliefweb.int/",
    "verified": true
  },
  {
    "id": "ACLED-1229B2ACE0",
    "date": "2021-04-12",
    "country": "DR Congo",
    "province": "South Kivu",
    "city": "Kalehe",
    "lat": -2.097,
    "lng": 28.905,
    "type": "violence-civilians",
    "severity": "critical",
    "fatalities": 73,
    "actor1": "Mayi Mayi Militia (Raia Mutomboki)",
    "actor2": "Civilians (Democratic Republic of Congo)",
    "title": "Around 12 April 2021 (between 1 April - 23 April), the Raia Mutomboki and suspected Nyatura militants killed 73 people (out of which 17 were women) in",
    "desc": "Around 12 April 2021 (between 1 April - 23 April), the Raia Mutomboki and suspected Nyatura militants killed 73 people (out of which 17 were women) in the territory of Kalehe (Sud-Kivu). Reports also suggest that 15,189 households were displaced as a result of these attacks (coded as another event). (来源: ACLED, 事件ID: DRC22277)",
    "source": "ACLED",
    "sourceUrl": "https://acleddata.com/data/",
    "verified": true
  },
  {
    "id": "ACLED-D07E5611A9",
    "date": "2021-01-05",
    "country": "DR Congo",
    "province": "North Kivu",
    "city": "Mwenda",
    "lat": 0.4167,
    "lng": 29.7667,
    "type": "battles",
    "severity": "critical",
    "fatalities": 50,
    "actor1": "Military Forces of the Democratic Republic of Congo (2019-)",
    "actor2": "ADF: Allied Democratic Forces",
    "title": "On 5 January 2021, the FARDC clashed with ADF militia combatants in Loselose village, near Mwenda (Beni, Nord-Kivu), following another military offens",
    "desc": "On 5 January 2021, the FARDC clashed with ADF militia combatants in Loselose village, near Mwenda (Beni, Nord-Kivu), following another military offensive after these rebels had occupied the village the previous week. This time the FARDC managed to drive the rebels out of the village. Reportedly, during their flight the ADF killed 50 hostages. Alternate reports suggest that 50 ADF bodies were uncovered at the scene. It is unclear whether these refer to the same bodies. (来源: ACLED, 事件ID: DRC19673)",
    "source": "ACLED",
    "sourceUrl": "https://acleddata.com/data/",
    "verified": true
  },
  {
    "id": "ACLED-8AA4915EDC",
    "date": "2020-04-15",
    "country": "DR Congo",
    "province": "North Kivu",
    "city": "Tongo",
    "lat": -1.2108,
    "lng": 29.2758,
    "type": "battles",
    "severity": "critical",
    "fatalities": 43,
    "actor1": "Military Forces of the Democratic Republic of Congo (2019-) Special Forces",
    "actor2": "FDLR: Democratic Forces for the Liberation of Rwanda",
    "title": "On 15 April 2020, FARDC clashed with FDLR in one of their strongholds in Kilinga (Gihondo Groupement), Rutshuru territory, killing 43 combatants inclu",
    "desc": "On 15 April 2020, FARDC clashed with FDLR in one of their strongholds in Kilinga (Gihondo Groupement), Rutshuru territory, killing 43 combatants including one high commander. (来源: ACLED, 事件ID: DRC16999)",
    "source": "ACLED",
    "sourceUrl": "https://acleddata.com/data/",
    "verified": true
  },
  {
    "id": "ACLED-8D54208267",
    "date": "2020-04-12",
    "country": "DR Congo",
    "province": "Ituri",
    "city": "Ituri",
    "lat": 1.8206,
    "lng": 30.7219,
    "type": "battles",
    "severity": "critical",
    "fatalities": 44,
    "actor1": "Military Forces of the Democratic Republic of Congo (2019-)",
    "actor2": "CODECO: Cooperative for Development of Congo",
    "title": "On 12 April 2020, CODECO militiamen clashed with FARDC elements in the locality of Ituri, resulting in 40 rebels and 4 soldiers killed. The military s",
    "desc": "On 12 April 2020, CODECO militiamen clashed with FARDC elements in the locality of Ituri, resulting in 40 rebels and 4 soldiers killed. The military seized several weapons. (来源: ACLED, 事件ID: DRC16988)",
    "source": "ACLED",
    "sourceUrl": "https://acleddata.com/data/",
    "verified": true
  },
  {
    "id": "ACLED-89A5199E0F",
    "date": "2020-03-21",
    "country": "DR Congo",
    "province": "North Kivu",
    "city": "Kamango",
    "lat": 0.666,
    "lng": 29.879,
    "type": "battles",
    "severity": "critical",
    "fatalities": 49,
    "actor1": "Military Forces of the Democratic Republic of Congo (2019-)",
    "actor2": "ADF: Allied Democratic Forces",
    "title": "Around 21 March 2020 (between 19 March - 23 March), FARDC forces clashed with ADF fighters near the localities of Kamango, Eringeti and Mbau (Nord-Kiv",
    "desc": "Around 21 March 2020 (between 19 March - 23 March), FARDC forces clashed with ADF fighters near the localities of Kamango, Eringeti and Mbau (Nord-Kivu). Following the clashes, Army forces conquered World Space, a former stronghold of ADF allies located in the area. 49 were killed in the clash, including 37 ADF fighters and 12 FARDC soldiers. (来源: ACLED, 事件ID: DRC16805)",
    "source": "ACLED",
    "sourceUrl": "https://acleddata.com/data/",
    "verified": true
  },
  {
    "id": "DRC-027",
    "date": "2020-02-15",
    "country": "DR Congo",
    "province": "Ituri",
    "city": "Djugu",
    "lat": 1.733,
    "lng": 30.5,
    "type": "violence-civilians",
    "severity": "critical",
    "fatalities": 92,
    "actor1": "CODECO",
    "actor2": "平民",
    "title": "【历史】2020年—伊图里省爆发大规模族群暴力",
    "desc": "2020年初，伊图里省伦杜(Lendu)和赫马(Hema)族群之间的暴力冲突急剧升级，CODECO民兵对赫马族村庄发动一系列致命袭击。冲突根源可追溯至殖民时期，涉及土地权属和矿产资源控制等深层矛盾。",
    "source": "ACLED",
    "sourceUrl": "https://acleddata.com/",
    "verified": true
  },
  {
    "id": "ACLED-DE118058CF",
    "date": "2020-02-02",
    "country": "DR Congo",
    "province": "North Kivu",
    "city": "Mandumbi",
    "lat": 0.7302,
    "lng": 29.3678,
    "type": "violence-civilians",
    "severity": "critical",
    "fatalities": 61,
    "actor1": "ADF: Allied Democratic Forces",
    "actor2": "Civilians (Democratic Republic of Congo)",
    "title": "On 2 February 2020, presumed ADF rebels reportedly attacked and killed sixty-one people in Mandumbi (Beni, Nord-Kivu).",
    "desc": "On 2 February 2020, presumed ADF rebels reportedly attacked and killed sixty-one people in Mandumbi (Beni, Nord-Kivu). (来源: ACLED, 事件ID: DRC18274)",
    "source": "ACLED",
    "sourceUrl": "https://acleddata.com/data/",
    "verified": true
  },
  {
    "id": "ACLED-C716323E38",
    "date": "2020-01-09",
    "country": "DR Congo",
    "province": "North Kivu",
    "city": "Beni",
    "lat": 0.4966,
    "lng": 29.4654,
    "type": "battles",
    "severity": "critical",
    "fatalities": 70,
    "actor1": "Military Forces of the Democratic Republic of Congo (2019-)",
    "actor2": "ADF: Allied Democratic Forces",
    "title": "On 9 January 2020, FARDC took back Madina (Beni) from the ADF. 40 fighters and 30 FARDC were killed during these clashes 70 other soldiers were injure",
    "desc": "On 9 January 2020, FARDC took back Madina (Beni) from the ADF. 40 fighters and 30 FARDC were killed during these clashes 70 other soldiers were injured . (来源: ACLED, 事件ID: DRC16339)",
    "source": "ACLED",
    "sourceUrl": "https://acleddata.com/data/",
    "verified": true
  },
  {
    "id": "ACLED-EC5EB3CB67",
    "date": "2019-12-07",
    "country": "DR Congo",
    "province": "South Kivu",
    "city": "Bugaru",
    "lat": -2.3382,
    "lng": 28.4412,
    "type": "battles",
    "severity": "critical",
    "fatalities": 52,
    "actor1": "Military Forces of the Democratic Republic of Congo (2019-)",
    "actor2": "CNRD: National Council for Renewal and Democracy",
    "title": "On 7 December 2019, the FARDC, supported by Mayi Mayi Raia Mutomboki Bipopa, Mayi Mayi Raia Mutomboki Hamakombo and Mayi Mayi Raia Mutomboki Lance Mut",
    "desc": "On 7 December 2019, the FARDC, supported by Mayi Mayi Raia Mutomboki Bipopa, Mayi Mayi Raia Mutomboki Hamakombo and Mayi Mayi Raia Mutomboki Lance Muteya, clashed with CNRD fighters at the village of Bugaru (Kalehe, Sud-Kivu). The attack killed 27 people in the ranks of CNRD, 12 FARDC soldiers and 13 on the side of the Raia Mutomboki. The assailants also looted the population's property. (来源: ACLED, 事件ID: DRC44312)",
    "source": "ACLED",
    "sourceUrl": "https://acleddata.com/data/",
    "verified": true
  },
  {
    "id": "ACLED-445B633917",
    "date": "2019-10-30",
    "country": "DR Congo",
    "province": "North Kivu",
    "city": "Beni",
    "lat": 0.4966,
    "lng": 29.4654,
    "type": "battles",
    "severity": "critical",
    "fatalities": 80,
    "actor1": "Military Forces of the Democratic Republic of Congo (2019-)",
    "actor2": "ADF: Allied Democratic Forces",
    "title": "Since 30 October 2019, military forces killed 80 elements of the ADF including 4 of their commanders in the area of Beni. The military got back the lo",
    "desc": "Since 30 October 2019, military forces killed 80 elements of the ADF including 4 of their commanders in the area of Beni. The military got back the locations of Mayangose, Tsotsota, Mwalika and Kididiwe. (来源: ACLED, 事件ID: DRC16156)",
    "source": "ACLED",
    "sourceUrl": "https://acleddata.com/data/",
    "verified": true
  },
  {
    "id": "ACLED-46BB05829F",
    "date": "2019-06-12",
    "country": "DR Congo",
    "province": "Ituri",
    "city": "Tche",
    "lat": 1.669,
    "lng": 30.5202,
    "type": "violence-civilians",
    "severity": "critical",
    "fatalities": 140,
    "actor1": "Lendu Ethnic Militia (Democratic Republic of Congo)",
    "actor2": "Civilians (Democratic Republic of Congo)",
    "title": "On 12 June 2019, in Tche, suspected Lendu Ethnic Militia attacked Hema civilians with firearms and machetes. 140 bodies of massacred civilians were di",
    "desc": "On 12 June 2019, in Tche, suspected Lendu Ethnic Militia attacked Hema civilians with firearms and machetes. 140 bodies of massacred civilians were discovered by civil society on 16 June. The killings is part of ongoing inter-ethnic violence in Djugu area between Hema and Lendu. (来源: ACLED, 事件ID: DRC14647)",
    "source": "ACLED",
    "sourceUrl": "https://acleddata.com/data/",
    "verified": true
  },
  {
    "id": "ACLED-5AC2F61AFF",
    "date": "2019-06-11",
    "country": "DR Congo",
    "province": "Ituri",
    "city": "Tche",
    "lat": 1.669,
    "lng": 30.5202,
    "type": "violence-civilians",
    "severity": "high",
    "fatalities": 38,
    "actor1": "Lendu Ethnic Militia (Democratic Republic of Congo)",
    "actor2": "Civilians (Democratic Republic of Congo)",
    "title": "On 11 June 2019, in Tche, suspected Lendu Ethnic Militia attacked Hema civilians with firearms and machetes killing 38 civilians. The killings is part",
    "desc": "On 11 June 2019, in Tche, suspected Lendu Ethnic Militia attacked Hema civilians with firearms and machetes killing 38 civilians. The killings is part of ongoing inter-ethnic violence in Djugu area between Hema and Lendu. (来源: ACLED, 事件ID: DRC14642)",
    "source": "ACLED",
    "sourceUrl": "https://acleddata.com/data/",
    "verified": true
  },
  {
    "id": "ACLED-B2BA4F70D1",
    "date": "2019-05-15",
    "country": "DR Congo",
    "province": "Kinshasa",
    "city": "Kinshasa",
    "lat": -4.325,
    "lng": 15.3222,
    "type": "violence-civilians",
    "severity": "critical",
    "fatalities": 48,
    "actor1": "Military Forces of the Democratic Republic of Congo (2019-)",
    "actor2": "Civilians (Democratic Republic of Congo)",
    "title": "In May [coded to 15 May], across DRC [coded to Kinshasa], Joint Juman Rights Office / MONUSCO reported that at least 48 extrajudicial killings were ca",
    "desc": "In May [coded to 15 May], across DRC [coded to Kinshasa], Joint Juman Rights Office / MONUSCO reported that at least 48 extrajudicial killings were carried out by state security forces in May. (来源: ACLED, 事件ID: DRC14783)",
    "source": "ACLED",
    "sourceUrl": "https://acleddata.com/data/",
    "verified": true
  },
  {
    "id": "ACLED-4B636F8F7A",
    "date": "2018-12-17",
    "country": "DR Congo",
    "province": "Mai-Ndombe",
    "city": "Bongende",
    "lat": -2.0325,
    "lng": 16.4276,
    "type": "violence-civilians",
    "severity": "critical",
    "fatalities": 348,
    "actor1": "Batende Ethnic Militia (Democratic Republic of Congo)",
    "actor2": "Civilians (Democratic Republic of Congo)",
    "title": "17 December. Following the attack on Yumbi city on 16/12, suspected Batende militia members attacked Bongende, Yumbi. The assailants mutilated the vic",
    "desc": "17 December. Following the attack on Yumbi city on 16/12, suspected Batende militia members attacked Bongende, Yumbi. The assailants mutilated the victims, removing limbs and sexual organs of men, women and children. Fetuses were cut out of pregnant women. At least one woman was raped and two children were reportedly abducted. A MONUSCO investigation confirmed 348 fatalities in Bongende, however, they suspected the actual number to be higher. Investigations found that the attacked on the Banunu were likely planned in advance and soldiers participated in the attacks on Bongende. (来源: ACLED, 事件ID: DRC13360)",
    "source": "ACLED",
    "sourceUrl": "https://acleddata.com/data/",
    "verified": true
  },
  {
    "id": "ACLED-4DA37793D7",
    "date": "2018-12-16",
    "country": "DR Congo",
    "province": "Mai-Ndombe",
    "city": "Yumbi",
    "lat": -1.8833,
    "lng": 16.5333,
    "type": "battles",
    "severity": "critical",
    "fatalities": 170,
    "actor1": "Batende Ethnic Militia (Democratic Republic of Congo)",
    "actor2": "Banunu Ethnic Militia (Democratic Republic of Congo)",
    "title": "16 December. A group of 3,000 armed Batende attacked Yumbi city - particularly the neighborhoods of Noyi, Bolu, Likolo, and Ntsentseke. Local police m",
    "desc": "16 December. A group of 3,000 armed Batende attacked Yumbi city - particularly the neighborhoods of Noyi, Bolu, Likolo, and Ntsentseke. Local police members participated along the Batende (the head of the police had disarmed Banunu officers prior to the attack). Armed Banunu members retliated in some areas with support from a member of the naval forces. Civilians were shot, stabbed, mutilated, and burned to death; over 900 properties were damaged including homes, schools and churches. A MONUSCO investigation confirmed 170 fatalities, primarily from the Banunu community (the number may be higher due to uncounted bodies dumped into the river). The attack came after a communal dispute over the burial of the Banunu's customary chief on land belonging to Batende on 14/12. Local CSOs indicate that the group's political allegiances of the Batende with the FCC and Banunu with the Lamuka Coalition exacerbated the dispute. (来源: ACLED, 事件ID: DRC13359)",
    "source": "ACLED",
    "sourceUrl": "https://acleddata.com/data/",
    "verified": true
  },
  {
    "id": "ACLED-9EDB1953F8",
    "date": "2018-11-14",
    "country": "DR Congo",
    "province": "North Kivu",
    "city": "Kididiwe",
    "lat": 0.5119,
    "lng": 29.55,
    "type": "battles",
    "severity": "critical",
    "fatalities": 61,
    "actor1": "Military Forces of the Democratic Republic of Congo (2001-2019)",
    "actor2": "ADF: Allied Democratic Forces",
    "title": "On 14 November 2018, in Kididiwe, joint FARDC-MONUSCO troops recaptured a former FARDC camp from ADF militiamen. During the operation, 7 United Nation",
    "desc": "On 14 November 2018, in Kididiwe, joint FARDC-MONUSCO troops recaptured a former FARDC camp from ADF militiamen. During the operation, 7 United Nations peacekeepers were killed and 10 wounded, while 2 were still missing in action. FARDC reported that 14 soldiers had been killed, 29 had been wounded and 12 were still missing in action. An estimated 40 to 50 ADF combatants were killed. (来源: ACLED, 事件ID: DRC13070)",
    "source": "ACLED",
    "sourceUrl": "https://acleddata.com/data/",
    "verified": true
  },
  {
    "id": "ACLED-375DE95F63",
    "date": "2018-02-08",
    "country": "DR Congo",
    "province": "Tanganyika",
    "city": "Tanganyika",
    "lat": -7.0446,
    "lng": 29.7773,
    "type": "battles",
    "severity": "critical",
    "fatalities": 44,
    "actor1": "Military Forces of the Democratic Republic of Congo (2001-2019)",
    "actor2": "Mayi Mayi Militia (Yakutumba)",
    "title": "08 February. General Yav announced that FARDC operations had resulted in the death of 83 Mai-Mai Yakutumba elements and 6 FARDC soldiers and the captu",
    "desc": "08 February. General Yav announced that FARDC operations had resulted in the death of 83 Mai-Mai Yakutumba elements and 6 FARDC soldiers and the capture of 120 Mai-Mai elements. He added that almost all the localities formerly under the control of the armed group had been recovered by FARDC, including the Ubwari Peninsula and the coastline of Lake Tanganyika from Kalemie to Uvira. Date(s) of operations not known. (来源: ACLED, 事件ID: DRC12431)",
    "source": "ACLED",
    "sourceUrl": "https://acleddata.com/data/",
    "verified": true
  },
  {
    "id": "ACLED-1C06031B15",
    "date": "2018-02-08",
    "country": "DR Congo",
    "province": "South Kivu",
    "city": "Ubwari Peninsula",
    "lat": -4.119,
    "lng": 29.2408,
    "type": "battles",
    "severity": "critical",
    "fatalities": 44,
    "actor1": "Military Forces of the Democratic Republic of Congo (2001-2019)",
    "actor2": "Mayi Mayi Militia (Yakutumba)",
    "title": "08 February. General Yav announced that FARDC operations had resulted in the death of 83 Mai-Mai Yakutumba elements and 6 FARDC soldiers and the captu",
    "desc": "08 February. General Yav announced that FARDC operations had resulted in the death of 83 Mai-Mai Yakutumba elements and 6 FARDC soldiers and the capture of 120 Mai-Mai elements. He added that almost all the localities formerly under the control of the armed group had been recovered by FARDC, including the Ubwari Peninsula and the coastline of Lake Tanganyika from Kalemie to Uvira. Date(s) of operations not known. (来源: ACLED, 事件ID: DRC12432)",
    "source": "ACLED",
    "sourceUrl": "https://acleddata.com/data/",
    "verified": true
  },
  {
    "id": "ACLED-5BBC7EEA6B",
    "date": "2017-12-22",
    "country": "DR Congo",
    "province": "North Kivu",
    "city": "Eringeti",
    "lat": 0.8519,
    "lng": 29.6124,
    "type": "remote-violence",
    "severity": "critical",
    "fatalities": 100,
    "actor1": "Military Forces of the Democratic Republic of Congo (2001-2019)",
    "actor2": "ADF: Allied Democratic Forces",
    "title": "The Ugandan army announced on December 22nd that it had undertaken a preventive strike on the positions of ADF rebels along the Uganda-DRC border, in ",
    "desc": "The Ugandan army announced on December 22nd that it had undertaken a preventive strike on the positions of ADF rebels along the Uganda-DRC border, in Eringiti (8 ADF bases were destroyed: Madina, Canada, Tadia, Popoke, Makayoba, Kaynama, Ngiti and Kikingi). Air force and long-range artillery were used (operation Tuugo). This came after the establishment of a mechanism to share information on ADF with the DRC forces. On Monday 25th, the Ugandan army claimed to have killed 100 rebels. (来源: ACLED, 事件ID: DRC11721)",
    "source": "ACLED",
    "sourceUrl": "https://acleddata.com/data/",
    "verified": true
  },
  {
    "id": "ACLED-935EB01FD1",
    "date": "2017-07-12",
    "country": "DR Congo",
    "province": "Kasai",
    "city": "Tshisuaka",
    "lat": -7.0167,
    "lng": 21.2333,
    "type": "violence-civilians",
    "severity": "critical",
    "fatalities": 310,
    "actor1": "Unidentified Armed Group (Democratic Republic of Congo)",
    "actor2": "Civilians (Democratic Republic of Congo)",
    "title": "31 mass graves were found at Diboko. Est 10 bodies per grave",
    "desc": "31 mass graves were found at Diboko. Est 10 bodies per grave (来源: ACLED, 事件ID: DRC11321)",
    "source": "ACLED",
    "sourceUrl": "https://acleddata.com/data/",
    "verified": true
  },
  {
    "id": "ACLED-C8B9CB67C5",
    "date": "2017-07-12",
    "country": "DR Congo",
    "province": "Kasai",
    "city": "Sumbula",
    "lat": -7.1329,
    "lng": 21.2259,
    "type": "violence-civilians",
    "severity": "critical",
    "fatalities": 70,
    "actor1": "Unidentified Armed Group (Democratic Republic of Congo)",
    "actor2": "Civilians (Democratic Republic of Congo)",
    "title": "7 mass graves were found at Sumbula. Est 10 bodies per grave",
    "desc": "7 mass graves were found at Sumbula. Est 10 bodies per grave (来源: ACLED, 事件ID: DRC11320)",
    "source": "ACLED",
    "sourceUrl": "https://acleddata.com/data/",
    "verified": true
  },
  {
    "id": "ACLED-EE0E7A0ECA",
    "date": "2017-04-24",
    "country": "DR Congo",
    "province": "Kasai",
    "city": "Luebo",
    "lat": -5.35,
    "lng": 21.4167,
    "type": "violence-civilians",
    "severity": "critical",
    "fatalities": 116,
    "actor1": "Bana Mura",
    "actor2": "Civilians (Democratic Republic of Congo)",
    "title": "Cinq village in Kasai was attacked by Bana Mura militia organised by FARDC commanders. Luba and Lulua villagers were rounded up and shot or killed by ",
    "desc": "Cinq village in Kasai was attacked by Bana Mura militia organised by FARDC commanders. Luba and Lulua villagers were rounded up and shot or killed by machetes. Villagers who tried to escape were stopped at a military checkpoint on the road out of the village and killed or raped. Bana Mura invaded the hospital, killing some patients and medical personnel. The UN has corroborated 116 deaths in Cinq. Many of the villagers who escaped have been mutilated. The few Kamwina present in the village fled, without reported clashes with the Bana Mura. (来源: ACLED, 事件ID: DRC11058)",
    "source": "ACLED",
    "sourceUrl": "https://acleddata.com/data/",
    "verified": true
  },
  {
    "id": "ACLED-632C817A18",
    "date": "2017-04-15",
    "country": "DR Congo",
    "province": "Kasai",
    "city": "Kamonia",
    "lat": -6.8667,
    "lng": 20.9333,
    "type": "violence-civilians",
    "severity": "critical",
    "fatalities": 100,
    "actor1": "Chokwe Ethnic Militia (Democratic Republic of Congo)",
    "actor2": "Civilians (Democratic Republic of Congo)",
    "title": "Chokwe militia have been targeting Tshiluba-speaking tribes, especially the Bindji and Lele, in recent weeks. Fatality estimates range from dozens or ",
    "desc": "Chokwe militia have been targeting Tshiluba-speaking tribes, especially the Bindji and Lele, in recent weeks. Fatality estimates range from dozens or hundreds to up to 190. (来源: ACLED, 事件ID: DRC11028)",
    "source": "ACLED",
    "sourceUrl": "https://acleddata.com/data/",
    "verified": true
  },
  {
    "id": "ACLED-3C218493CE",
    "date": "2016-12-04",
    "country": "DR Congo",
    "province": "Tanganyika",
    "city": "Rutuku",
    "lat": -6.2197,
    "lng": 29.3147,
    "type": "violence-civilians",
    "severity": "high",
    "fatalities": 35,
    "actor1": "Batwa Ethnic Militia (Democratic Republic of Congo)",
    "actor2": "Civilians (Democratic Republic of Congo)",
    "title": "A Batwa ethnic militia killed at least 35, injured 25, and burned houses in the Rutuku area near Kalemie. All of those killed were reportedly Bantus, ",
    "desc": "A Batwa ethnic militia killed at least 35, injured 25, and burned houses in the Rutuku area near Kalemie. All of those killed were reportedly Bantus, while many others have fled the area. (来源: ACLED, 事件ID: DRC10671)",
    "source": "ACLED",
    "sourceUrl": "https://acleddata.com/data/",
    "verified": true
  },
  {
    "id": "ACLED-39848EAD04",
    "date": "2016-11-27",
    "country": "DR Congo",
    "province": "North Kivu",
    "city": "Luofu",
    "lat": -0.6147,
    "lng": 29.113,
    "type": "violence-civilians",
    "severity": "high",
    "fatalities": 34,
    "actor1": "Mayi Mayi Militia (Mazembe)",
    "actor2": "Civilians (Democratic Republic of Congo)",
    "title": "At least 34 civilians, mostly ethnic Hutus, were killed with machetes and guns by about 50 Mayi Mayi Mazembe militiamen (which is a primarily Nande mi",
    "desc": "At least 34 civilians, mostly ethnic Hutus, were killed with machetes and guns by about 50 Mayi Mayi Mazembe militiamen (which is a primarily Nande militia) in an attack on an IDP camp. The killings took place in the Luhanga area of Lubero. Another report claimed one of those killed was a police officer. (来源: ACLED, 事件ID: DRC10649)",
    "source": "ACLED",
    "sourceUrl": "https://acleddata.com/data/",
    "verified": true
  },
  {
    "id": "ACLED-1BE5AC5E73",
    "date": "2016-09-19",
    "country": "DR Congo",
    "province": "Kinshasa",
    "city": "Kinshasa",
    "lat": -4.325,
    "lng": 15.3222,
    "type": "strategic-dev",
    "severity": "high",
    "fatalities": 29,
    "actor1": "Rioters (Democratic Republic of Congo)",
    "actor2": "Police Forces of the Democratic Republic of Congo (2001-2019)",
    "title": "14 civilians and 3 police officers were reported killed in clashes which broke out during protests organized by the OCR against elections delays by Pr",
    "desc": "14 civilians and 3 police officers were reported killed in clashes which broke out during protests organized by the OCR against elections delays by President Kabilas government. One of the police officers was allegedly burnt alive. The protests were reported to have drawn thousands of participants. The HQs of several of the ruling coalitions parties (including the RCD,PPRD, ATD, ARC and CNC) were also burnt down by opposition demonstrators, but no casualties were reported from these acts. 49 civilians were said to have been killed in the violence in Kinshasa in total. (来源: ACLED, 事件ID: DRC10481)",
    "source": "ACLED",
    "sourceUrl": "https://acleddata.com/data/",
    "verified": true
  },
  {
    "id": "ACLED-CC9E2940C8",
    "date": "2016-08-27",
    "country": "DR Congo",
    "province": "North Kivu",
    "city": "Beni",
    "lat": 0.4966,
    "lng": 29.4654,
    "type": "battles",
    "severity": "critical",
    "fatalities": 70,
    "actor1": "Military Forces of the Democratic Republic of Congo (2001-2019)",
    "actor2": "ADF: Allied Democratic Forces",
    "title": "Several villages, including Kambi ya Miba, Totolito and Mbau, about 40km northeast of Beni, have been recaptured by Congolese forces. A FARDC colonel ",
    "desc": "Several villages, including Kambi ya Miba, Totolito and Mbau, about 40km northeast of Beni, have been recaptured by Congolese forces. A FARDC colonel claimed that 70 casualties had been taken in one day to capture Kambi ya Miba. No other casualties were reported. (来源: ACLED, 事件ID: DRC10423)",
    "source": "ACLED",
    "sourceUrl": "https://acleddata.com/data/",
    "verified": true
  },
  {
    "id": "ACLED-5C4EB8D8FD",
    "date": "2016-06-15",
    "country": "DR Congo",
    "province": "North Kivu",
    "city": "Beni",
    "lat": 0.4966,
    "lng": 29.4654,
    "type": "battles",
    "severity": "critical",
    "fatalities": 45,
    "actor1": "Military Forces of the Democratic Republic of Congo (2001-2019)",
    "actor2": "ADF: Allied Democratic Forces",
    "title": "14 FARDC soldiers and 37 ADF rebels have been killed in operations against the ADF since May (the deaths of 6 ADF rebels and 1 soldier coded in anothe",
    "desc": "14 FARDC soldiers and 37 ADF rebels have been killed in operations against the ADF since May (the deaths of 6 ADF rebels and 1 soldier coded in another event). 15 other rebels were captured, along with weapons and ammunitions and some roadside bombs. MONUSCO supported FARDC in these operations. One of the ADF rebels killed was the 2nd in command of the group (killed on June 13, coded in another event). (来源: ACLED, 事件ID: DRC10229)",
    "source": "ACLED",
    "sourceUrl": "https://acleddata.com/data/",
    "verified": true
  },
  {
    "id": "ACLED-E154C0DF8C",
    "date": "2015-11-30",
    "country": "DR Congo",
    "province": "North Kivu",
    "city": "Eringeti",
    "lat": 0.8519,
    "lng": 29.6124,
    "type": "battles",
    "severity": "high",
    "fatalities": 22,
    "actor1": "Military Forces of the Democratic Republic of Congo (2001-2019)",
    "actor2": "ADF: Allied Democratic Forces",
    "title": "On 30 November 2015, ADF rebels dislodged FARDC and MONUSCO regained control of Eringeti (Beni, Nord-Kivu) during clashes that started on the previous",
    "desc": "On 30 November 2015, ADF rebels dislodged FARDC and MONUSCO regained control of Eringeti (Beni, Nord-Kivu) during clashes that started on the previous day (coded separately). The rebels attack stretched from Makembi to Eringeti and simultaneously targeted a FARDC position, a MONUSCO base, a hospital in Eringeti, and the office of the PNC in Beni territory. During the 2 days of clashes, 1 UN peacekeeper, 7 soldiers, 10 civilians and 21 rebels were killed, while 1 peacekeeper and 4 soldiers were injured. 5 more people believe to have been killed during the fighting were found a few days later. During the violence at least 43 homes were also burned. At least 2,000 people have fled following the fighting. Fatalities coded as 44 (1 UN PKO, 7 soldiers, 10 civilians, 21 rebels and 5 more people), split into 2 events, coded as 22 in this event. (来源: ACLED, 事件ID: DRC9730)",
    "source": "ACLED",
    "sourceUrl": "https://acleddata.com/data/",
    "verified": true
  },
  {
    "id": "ACLED-0FDE977F90",
    "date": "2015-11-29",
    "country": "DR Congo",
    "province": "North Kivu",
    "city": "Eringeti",
    "lat": 0.8519,
    "lng": 29.6124,
    "type": "battles",
    "severity": "high",
    "fatalities": 22,
    "actor1": "Military Forces of the Democratic Republic of Congo (2001-2019)",
    "actor2": "ADF: Allied Democratic Forces",
    "title": "On 29 November 2015, ADF clashes with FARDC and MONUSCO and pushed them out in Eringeti (Beni, Nord-Kivu). The rebels attack stretched from Makembi to",
    "desc": "On 29 November 2015, ADF clashes with FARDC and MONUSCO and pushed them out in Eringeti (Beni, Nord-Kivu). The rebels attack stretched from Makembi to Eringeti and simultaneously targeted a FARDC position, a MONUSCO base, a hospital in Eringeti, and the office of the PNC in Beni territory. Government Forces regained control of Eringeti on the following day (coded separately). During the 2 days of clashes, 1 UN peacekeeper, 7 soldiers, 10 civilians and 21 rebels were killed, while 1 peacekeeper and 4 soldiers were injured. 5 more people believe to have been killed during the fighting were found a few days later. During the violence at least 43 homes were also burned. At least 2,000 people have fled following the fighting. Fatalities coded as 44 (1 UN PKO, 7 soldiers, 10 civilians, 21 rebels and 5 more people), split into 2 events, coded as 22 in this event. (来源: ACLED, 事件ID: DRC9727)",
    "source": "ACLED",
    "sourceUrl": "https://acleddata.com/data/",
    "verified": true
  },
  {
    "id": "ACLED-02E669DECE",
    "date": "2015-05-12",
    "country": "DR Congo",
    "province": "North Kivu",
    "city": "Mbau",
    "lat": 0.6534,
    "lng": 29.4956,
    "type": "violence-civilians",
    "severity": "high",
    "fatalities": 37,
    "actor1": "ADF: Allied Democratic Forces",
    "actor2": "Civilians (Democratic Republic of Congo)",
    "title": "As many as 37 people were killed by armed men wielding axes and machetes in two villages, Sabu and Mapiki, in the Mbau area. Thousands of people have ",
    "desc": "As many as 37 people were killed by armed men wielding axes and machetes in two villages, Sabu and Mapiki, in the Mbau area. Thousands of people have fled following the violence. The attack is attributed to the ADF. (来源: ACLED, 事件ID: DRC9257)",
    "source": "ACLED",
    "sourceUrl": "https://acleddata.com/data/",
    "verified": true
  },
  {
    "id": "ACLED-A9DC69C045",
    "date": "2015-04-15",
    "country": "DR Congo",
    "province": "Ituri",
    "city": "Bango",
    "lat": 1.094,
    "lng": 29.1523,
    "type": "battles",
    "severity": "high",
    "fatalities": 23,
    "actor1": "Military Forces of the Democratic Republic of Congo (2001-2019)",
    "actor2": "ADF: Allied Democratic Forces",
    "title": "FARDC soldiers have allegedly discovered between 4-5 mass graves with at least 47 bodies after taking control of an ADF camp in the Bango area. The id",
    "desc": "FARDC soldiers have allegedly discovered between 4-5 mass graves with at least 47 bodies after taking control of an ADF camp in the Bango area. The identity of the victims is unknown but is currently speculated to either be ADF militants killed in clashes with the military or civilians executed by the rebels. (来源: ACLED, 事件ID: DRC9182)",
    "source": "ACLED",
    "sourceUrl": "https://acleddata.com/data/",
    "verified": true
  },
  {
    "id": "ACLED-A69F1A2027",
    "date": "2015-04-04",
    "country": "DR Congo",
    "province": "Kinshasa",
    "city": "Kinshasa - Maluku",
    "lat": -4.3588,
    "lng": 15.3308,
    "type": "violence-civilians",
    "severity": "critical",
    "fatalities": 420,
    "actor1": "Unidentified Armed Group (Democratic Republic of Congo)",
    "actor2": "Civilians (Democratic Republic of Congo)",
    "title": "Around 420 bodies (allegedly two weeks old) were found in a mass grave in the Fula Fula cemetery of Maluka in the Kinshasa area by residents. MONUSCO ",
    "desc": "Around 420 bodies (allegedly two weeks old) were found in a mass grave in the Fula Fula cemetery of Maluka in the Kinshasa area by residents. MONUSCO has been informed and asked prosecutors to investigat the issue. (来源: ACLED, 事件ID: DRC9165)",
    "source": "ACLED",
    "sourceUrl": "https://acleddata.com/data/",
    "verified": true
  },
  {
    "id": "ACLED-C6BA1CBAAE",
    "date": "2014-12-06",
    "country": "DR Congo",
    "province": "North Kivu",
    "city": "Oicha",
    "lat": 0.7,
    "lng": 29.5167,
    "type": "violence-civilians",
    "severity": "high",
    "fatalities": 36,
    "actor1": "ADF: Allied Democratic Forces",
    "actor2": "Civilians (Democratic Republic of Congo)",
    "title": "ADF-NALU rebels killed 36 people with machetes and axes in the Aili district of Oicha. 2 people were also injured and 2 other abducted.",
    "desc": "ADF-NALU rebels killed 36 people with machetes and axes in the Aili district of Oicha. 2 people were also injured and 2 other abducted. (来源: ACLED, 事件ID: DRC8904)",
    "source": "ACLED",
    "sourceUrl": "https://acleddata.com/data/",
    "verified": true
  },
  {
    "id": "ACLED-8353147F79",
    "date": "2014-11-20",
    "country": "DR Congo",
    "province": "North Kivu",
    "city": "Mbau",
    "lat": 0.6534,
    "lng": 29.4956,
    "type": "violence-civilians",
    "severity": "critical",
    "fatalities": 58,
    "actor1": "ADF: Allied Democratic Forces",
    "actor2": "Civilians (Democratic Republic of Congo)",
    "title": "Survivors of an attack allegedly by the ADF-NALU between Mbau and Beni say between 50-80 people were killed after the ADF soldiers pretended to be FAR",
    "desc": "Survivors of an attack allegedly by the ADF-NALU between Mbau and Beni say between 50-80 people were killed after the ADF soldiers pretended to be FARDC members to gain their trust. The victims were killed using 'crude weapons' over about 5 hours. The official death toll is 58: 49 men, 7 women and 2 children. (来源: ACLED, 事件ID: DRC8876)",
    "source": "ACLED",
    "sourceUrl": "https://acleddata.com/data/",
    "verified": true
  },
  {
    "id": "ACLED-75B3CFBB8E",
    "date": "2014-06-06",
    "country": "DR Congo",
    "province": "South Kivu",
    "city": "Mutarule",
    "lat": -2.9952,
    "lng": 29.0945,
    "type": "violence-civilians",
    "severity": "high",
    "fatalities": 38,
    "actor1": "Unidentified Armed Group (Democratic Republic of Congo)",
    "actor2": "Civilians (Democratic Republic of Congo)",
    "title": "Unknown armed men killed 38 people and injured 24 during an attack on Mutarule village. The attack was reportedly in reprisal for cattle raids. All vi",
    "desc": "Unknown armed men killed 38 people and injured 24 during an attack on Mutarule village. The attack was reportedly in reprisal for cattle raids. All victims were reportedly of the Bafuliru ethnic group. Some local media blamed the attacks on rebels from Burundis National Liberation Forces (FNL). Military and MONUSCO forces were aware of the attack but failed to intervene. (来源: ACLED, 事件ID: DRC8303)",
    "source": "ACLED",
    "sourceUrl": "https://acleddata.com/data/",
    "verified": true
  },
  {
    "id": "ACLED-6FBAFE7153",
    "date": "2014-02-01",
    "country": "DR Congo",
    "province": "North Kivu",
    "city": "Goma",
    "lat": -1.6566,
    "lng": 29.2085,
    "type": "violence-civilians",
    "severity": "critical",
    "fatalities": 70,
    "actor1": "Unidentified Armed Group (Democratic Republic of Congo)",
    "actor2": "Civilians (Democratic Republic of Congo)",
    "title": "UN sources revealed that an armed group had summarily executed 70 civilians in later January/early February.",
    "desc": "UN sources revealed that an armed group had summarily executed 70 civilians in later January/early February. (来源: ACLED, 事件ID: DRC7953)",
    "source": "ACLED",
    "sourceUrl": "https://acleddata.com/data/",
    "verified": true
  },
  {
    "id": "ACLED-39F9E0B611",
    "date": "2014-01-30",
    "country": "DR Congo",
    "province": "North Kivu",
    "city": "Beni",
    "lat": 0.4966,
    "lng": 29.4654,
    "type": "battles",
    "severity": "high",
    "fatalities": 33,
    "actor1": "Military Forces of the Democratic Republic of Congo (2001-2019)",
    "actor2": "ADF: Allied Democratic Forces",
    "title": "ADF-NALU clashed with FARDC in a government crack-down on armed groups in Beni. 32 ADF-NALU killed. 1 soldier killed & 3 others injured. FARDC regaine",
    "desc": "ADF-NALU clashed with FARDC in a government crack-down on armed groups in Beni. 32 ADF-NALU killed. 1 soldier killed & 3 others injured. FARDC regained control of the strategic Mbau-Kamango axis in Beni. (来源: ACLED, 事件ID: DRC7945)",
    "source": "ACLED",
    "sourceUrl": "https://acleddata.com/data/",
    "verified": true
  },
  {
    "id": "ACLED-694D8B101A",
    "date": "2013-12-30",
    "country": "DR Congo",
    "province": "Haut-Katanga",
    "city": "Lubumbashi",
    "lat": -11.6596,
    "lng": 27.4741,
    "type": "violence-civilians",
    "severity": "critical",
    "fatalities": 110,
    "actor1": "Unidentified Armed Group (Democratic Republic of Congo)",
    "actor2": "Civilians (Democratic Republic of Congo)",
    "title": "Unidentified armed military men attacked the national television building in Lubumbashi. 24 assailants killed. In May 2014, International Federation f",
    "desc": "Unidentified armed military men attacked the national television building in Lubumbashi. 24 assailants killed. In May 2014, International Federation for Human Rights reported that ~250 civilians & 6 soldiers were killed in Katanga province (Lubumbashi, Kolwezi, Kindu) during the Dec 30 violence (来源: ACLED, 事件ID: DRC7866)",
    "source": "ACLED",
    "sourceUrl": "https://acleddata.com/data/",
    "verified": true
  },
  {
    "id": "ACLED-9846B246B9",
    "date": "2013-12-30",
    "country": "DR Congo",
    "province": "Lualaba",
    "city": "Kolwezi",
    "lat": -10.7167,
    "lng": 25.4725,
    "type": "violence-civilians",
    "severity": "critical",
    "fatalities": 108,
    "actor1": "Unidentified Armed Group (Democratic Republic of Congo)",
    "actor2": "Civilians (Democratic Republic of Congo)",
    "title": "Unidentified armed military men attacked Kolwezi. 23 assailants killed. In May 2014, International Federation for Human Rights reported that ~250 civi",
    "desc": "Unidentified armed military men attacked Kolwezi. 23 assailants killed. In May 2014, International Federation for Human Rights reported that ~250 civilians & 6 soldiers were killed in Katanga province (Lubumbashi, Kolwezi, Kindu) during the Dec 30 violence (来源: ACLED, 事件ID: DRC7865)",
    "source": "ACLED",
    "sourceUrl": "https://acleddata.com/data/",
    "verified": true
  },
  {
    "id": "ACLED-312F9D8BE6",
    "date": "2013-12-30",
    "country": "DR Congo",
    "province": "Maniema",
    "city": "Kindu",
    "lat": -2.9437,
    "lng": 25.9224,
    "type": "violence-civilians",
    "severity": "critical",
    "fatalities": 108,
    "actor1": "Unidentified Armed Group (Democratic Republic of Congo)",
    "actor2": "Civilians (Democratic Republic of Congo)",
    "title": "Unidentified armed military men attacked the airport in Kindu. 23 assailants killed. In May 2014, International Federation for Human Rights reported t",
    "desc": "Unidentified armed military men attacked the airport in Kindu. 23 assailants killed. In May 2014, International Federation for Human Rights reported that ~250 civilians & 6 soldiers were killed in Katanga province (Lubumbashi, Kolwezi, Kindu) during the Dec 30 violence (来源: ACLED, 事件ID: DRC7864)",
    "source": "ACLED",
    "sourceUrl": "https://acleddata.com/data/",
    "verified": true
  },
  {
    "id": "ACLED-F545491294",
    "date": "2013-12-30",
    "country": "DR Congo",
    "province": "Kinshasa",
    "city": "Kinshasa",
    "lat": -4.325,
    "lng": 15.3222,
    "type": "battles",
    "severity": "critical",
    "fatalities": 98,
    "actor1": "Unidentified Armed Group (Democratic Republic of Congo)",
    "actor2": "Military Forces of the Democratic Republic of Congo (2001-2019)",
    "title": "Armed men in Kinshasha attacked FARDC members at their General Office. Further armed men then attacked Ndjili national airport, also in Kinshasha. 24 ",
    "desc": "Armed men in Kinshasha attacked FARDC members at their General Office. Further armed men then attacked Ndjili national airport, also in Kinshasha. 24 assailants killed & 3 FARDC. In May 2014, International Federation for Human Rights reported that 71 civilians were killed in Kinshasa during the Dec 30 violence (来源: ACLED, 事件ID: DRC7863)",
    "source": "ACLED",
    "sourceUrl": "https://acleddata.com/data/",
    "verified": true
  },
  {
    "id": "ACLED-24F0F7A99E",
    "date": "2013-06-05",
    "country": "DR Congo",
    "province": "North Kivu",
    "city": "Pinga",
    "lat": -0.9839,
    "lng": 28.702,
    "type": "battles",
    "severity": "critical",
    "fatalities": 150,
    "actor1": "APCLS: Alliance of Patriots for a Free and Sovereign Congo",
    "actor2": "NDC: Nduma Defence of Congo",
    "title": "APCLS clashed with Mayi Mayi Cheka in Pinga. 150 killed since end of May.",
    "desc": "APCLS clashed with Mayi Mayi Cheka in Pinga. 150 killed since end of May. (来源: ACLED, 事件ID: DRC7453)",
    "source": "ACLED",
    "sourceUrl": "https://acleddata.com/data/",
    "verified": true
  },
  {
    "id": "ACLED-01242596EE",
    "date": "2012-11-15",
    "country": "DR Congo",
    "province": "South Kivu",
    "city": "Kibumba",
    "lat": -3.0,
    "lng": 28.4667,
    "type": "battles",
    "severity": "critical",
    "fatalities": 153,
    "actor1": "Military Forces of the Democratic Republic of Congo (2001-2019)",
    "actor2": "Military Forces of Rwanda (1994-)",
    "title": "3,500 Rwandan soldiers crossed the border to support M23 rebels in a battle with FARDC. 2 FARDC & 151 rebels killed.",
    "desc": "3,500 Rwandan soldiers crossed the border to support M23 rebels in a battle with FARDC. 2 FARDC & 151 rebels killed. (来源: ACLED, 事件ID: DRC6842)",
    "source": "ACLED",
    "sourceUrl": "https://acleddata.com/data/",
    "verified": true
  },
  {
    "id": "ACLED-F36D5BBB03",
    "date": "2012-07-26",
    "country": "DR Congo",
    "province": "North Kivu",
    "city": "Rumangabo",
    "lat": -1.3439,
    "lng": 29.3594,
    "type": "battles",
    "severity": "high",
    "fatalities": 32,
    "actor1": "Military Forces of the Democratic Republic of Congo (2001-2019)",
    "actor2": "M23: March 23 Movement",
    "title": "FARDC clash with M23 rebels in Rumangabo with tanks backed by attack helicopters. 32 FARDC killed over previous few days according to M23 spokesperson",
    "desc": "FARDC clash with M23 rebels in Rumangabo with tanks backed by attack helicopters. 32 FARDC killed over previous few days according to M23 spokesperson. (来源: ACLED, 事件ID: DRC6404)",
    "source": "ACLED",
    "sourceUrl": "https://acleddata.com/data/",
    "verified": true
  },
  {
    "id": "ACLED-4821ED7E4F",
    "date": "2012-05-24",
    "country": "DR Congo",
    "province": "North Kivu",
    "city": "Kitchanga",
    "lat": -1.2497,
    "lng": 29.0599,
    "type": "violence-civilians",
    "severity": "critical",
    "fatalities": 100,
    "actor1": "Unidentified Armed Group (Democratic Republic of Congo)",
    "actor2": "Civilians (Democratic Republic of Congo)",
    "title": "Unidentified group, suspected to be ex-CNDP led by Ntaganda or M23 movement attacked civilians in Katchanga killing around 100 people and injuring and",
    "desc": "Unidentified group, suspected to be ex-CNDP led by Ntaganda or M23 movement attacked civilians in Katchanga killing around 100 people and injuring and raping many. (来源: ACLED, 事件ID: DRC6113)",
    "source": "ACLED",
    "sourceUrl": "https://acleddata.com/data/",
    "verified": true
  },
  {
    "id": "ACLED-B02CB7E4C0",
    "date": "2012-05-13",
    "country": "DR Congo",
    "province": "South Kivu",
    "city": "Kalehe",
    "lat": -2.097,
    "lng": 28.905,
    "type": "violence-civilians",
    "severity": "high",
    "fatalities": 30,
    "actor1": "FDLR: Democratic Forces for the Liberation of Rwanda",
    "actor2": "Civilians (Democratic Republic of Congo)",
    "title": "Since the beginning of May FDLR killed at least 30 civilians in the area allegedly for collaborating with the forces of Raia Mutomboki according to OC",
    "desc": "Since the beginning of May FDLR killed at least 30 civilians in the area allegedly for collaborating with the forces of Raia Mutomboki according to OCHA. (来源: ACLED, 事件ID: DRC6093)",
    "source": "ACLED",
    "sourceUrl": "https://acleddata.com/data/",
    "verified": true
  },
  {
    "id": "ACLED-5799B81584",
    "date": "2012-02-01",
    "country": "DR Congo",
    "province": "Tshopo",
    "city": "Kisangani",
    "lat": 0.5147,
    "lng": 25.1896,
    "type": "violence-civilians",
    "severity": "high",
    "fatalities": 30,
    "actor1": "LRA: Lords Resistance Army",
    "actor2": "Civilians (Democratic Republic of Congo)",
    "title": "LRA rebels attacks several rural villages and displace civilians.",
    "desc": "LRA rebels attacks several rural villages and displace civilians. (来源: ACLED, 事件ID: DRC5960)",
    "source": "ACLED",
    "sourceUrl": "https://acleddata.com/data/",
    "verified": true
  },
  {
    "id": "ACLED-3F5C5EA5A7",
    "date": "2011-12-15",
    "country": "DR Congo",
    "province": "Haut-Lomami",
    "city": "Kamina",
    "lat": -8.7386,
    "lng": 24.9906,
    "type": "violence-civilians",
    "severity": "high",
    "fatalities": 24,
    "actor1": "Unidentified Armed Group (Democratic Republic of Congo)",
    "actor2": "Civilians (Democratic Republic of Congo)",
    "title": "An unidentified armed group of natives in Kamina attacked families from Kasai following a land dispute.",
    "desc": "An unidentified armed group of natives in Kamina attacked families from Kasai following a land dispute. (来源: ACLED, 事件ID: DRC5893)",
    "source": "ACLED",
    "sourceUrl": "https://acleddata.com/data/",
    "verified": true
  },
  {
    "id": "ACLED-B95AF00B63",
    "date": "2011-10-24",
    "country": "DR Congo",
    "province": "South Kivu",
    "city": "Fizi",
    "lat": -4.3011,
    "lng": 28.9441,
    "type": "battles",
    "severity": "high",
    "fatalities": 16,
    "actor1": "Mayi Mayi Militia (Yakutumba)",
    "actor2": "Military Forces of the Democratic Republic of Congo (2001-2019)",
    "title": "Mayi Mayi Militia (Yakutumba) clashed with FARDC in Fizi. 9 FARDC & 7 Mayi Mayi killed, 3 injured.",
    "desc": "Mayi Mayi Militia (Yakutumba) clashed with FARDC in Fizi. 9 FARDC & 7 Mayi Mayi killed, 3 injured. (来源: ACLED, 事件ID: DRC5794)",
    "source": "ACLED",
    "sourceUrl": "https://acleddata.com/data/",
    "verified": true
  },
  {
    "id": "ACLED-C277583FF7",
    "date": "2011-09-12",
    "country": "DR Congo",
    "province": "Lower Uele",
    "city": "Bili",
    "lat": 4.151,
    "lng": 25.1755,
    "type": "battles",
    "severity": "high",
    "fatalities": 16,
    "actor1": "Military Forces of the Democratic Republic of Congo (2001-2019)",
    "actor2": "Mbororo Ethnic Militia (Democratic Republic of Congo)",
    "title": "Mbororo Communal Militia clashed with elements of FARDC in Bakpolo, Bili. 1 FARDC killed & 15 militia.",
    "desc": "Mbororo Communal Militia clashed with elements of FARDC in Bakpolo, Bili. 1 FARDC killed & 15 militia. (来源: ACLED, 事件ID: DRC5690)",
    "source": "ACLED",
    "sourceUrl": "https://acleddata.com/data/",
    "verified": true
  },
  {
    "id": "ACLED-F9A2D2B52A",
    "date": "2011-08-30",
    "country": "DR Congo",
    "province": "South Kivu",
    "city": "Talama",
    "lat": -4.9847,
    "lng": 29.1181,
    "type": "battles",
    "severity": "critical",
    "fatalities": 40,
    "actor1": "Military Forces of the Democratic Republic of Congo (2001-2019)",
    "actor2": "Mayi Mayi Militia (Yakutumba)",
    "title": "FARDC clashed with Mayi Mayi Militia (Yakutumba), Mayi Mayi Militia (DRC), FDLR & FNL members & regained Talama. 40 Mayi Mayi killed.",
    "desc": "FARDC clashed with Mayi Mayi Militia (Yakutumba), Mayi Mayi Militia (DRC), FDLR & FNL members & regained Talama. 40 Mayi Mayi killed. (来源: ACLED, 事件ID: DRC5659)",
    "source": "ACLED",
    "sourceUrl": "https://acleddata.com/data/",
    "verified": true
  },
  {
    "id": "ACLED-7F2525B2C6",
    "date": "2011-08-08",
    "country": "DR Congo",
    "province": "Lomami",
    "city": "Kabinda",
    "lat": -6.1333,
    "lng": 24.4833,
    "type": "battles",
    "severity": "high",
    "fatalities": 30,
    "actor1": "Kabongo Communal Militia (Democratic Republic of Congo)",
    "actor2": "Lubangula Communal Militia (Democratic Republic of Congo)",
    "title": "Kabongo Communal Militia clashed with Lubangula Communal Militia following an unresolved conflict over fishing rights. 30 killed & houses burned.",
    "desc": "Kabongo Communal Militia clashed with Lubangula Communal Militia following an unresolved conflict over fishing rights. 30 killed & houses burned. (来源: ACLED, 事件ID: DRC5610)",
    "source": "ACLED",
    "sourceUrl": "https://acleddata.com/data/",
    "verified": true
  },
  {
    "id": "ACLED-75ECD74231",
    "date": "2010-11-16",
    "country": "DR Congo",
    "province": "North Kivu",
    "city": "Walikale",
    "lat": -1.428,
    "lng": 28.073,
    "type": "violence-civilians",
    "severity": "high",
    "fatalities": 23,
    "actor1": "FDLR: Democratic Forces for the Liberation of Rwanda",
    "actor2": "Civilians (Democratic Republic of Congo)",
    "title": "23 killed after FDLR attack truck",
    "desc": "23 killed after FDLR attack truck (来源: ACLED, 事件ID: DRC5024)",
    "source": "ACLED",
    "sourceUrl": "https://acleddata.com/data/",
    "verified": true
  },
  {
    "id": "ACLED-533F0DD9EC",
    "date": "2010-07-16",
    "country": "DR Congo",
    "province": "North Kivu",
    "city": "Beni",
    "lat": 0.4966,
    "lng": 29.4654,
    "type": "violence-civilians",
    "severity": "high",
    "fatalities": 12,
    "actor1": "ADF: Allied Democratic Forces",
    "actor2": "Civilians (Democratic Republic of Congo)",
    "title": "Around 12 people executed by ADF-NALU between 11-16 July. The two organizations are Ugandan rebel groups whose base of operations is near the CAR/Ugan",
    "desc": "Around 12 people executed by ADF-NALU between 11-16 July. The two organizations are Ugandan rebel groups whose base of operations is near the CAR/Uganda border. (来源: ACLED, 事件ID: DRC4960)",
    "source": "ACLED",
    "sourceUrl": "https://acleddata.com/data/",
    "verified": true
  },
  {
    "id": "ACLED-9F3C0BE6B2",
    "date": "2010-07-15",
    "country": "DR Congo",
    "province": "North Kivu",
    "city": "Eringeti",
    "lat": 0.8519,
    "lng": 29.6124,
    "type": "battles",
    "severity": "high",
    "fatalities": 22,
    "actor1": "Military Forces of the Democratic Republic of Congo (2001-2019)",
    "actor2": "ADF: Allied Democratic Forces",
    "title": "Military attack village held by rebels, 22 rebels killed, 4 captured, 3 FARDC killed, over 2 days",
    "desc": "Military attack village held by rebels, 22 rebels killed, 4 captured, 3 FARDC killed, over 2 days (来源: ACLED, 事件ID: DRC4958)",
    "source": "ACLED",
    "sourceUrl": "https://acleddata.com/data/",
    "verified": true
  },
  {
    "id": "ACLED-8200DC4118",
    "date": "2010-07-14",
    "country": "DR Congo",
    "province": "North Kivu",
    "city": "Eringeti",
    "lat": 0.8519,
    "lng": 29.6124,
    "type": "battles",
    "severity": "high",
    "fatalities": 25,
    "actor1": "Military Forces of the Democratic Republic of Congo (2001-2019)",
    "actor2": "ADF: Allied Democratic Forces",
    "title": "Military attack village held by rebels, 22 rebels killed, 4 captured, 3 FARDC killed, over 2 days",
    "desc": "Military attack village held by rebels, 22 rebels killed, 4 captured, 3 FARDC killed, over 2 days (来源: ACLED, 事件ID: DRC4956)",
    "source": "ACLED",
    "sourceUrl": "https://acleddata.com/data/",
    "verified": true
  },
  {
    "id": "ACLED-49BD46BCE7",
    "date": "2010-07-12",
    "country": "DR Congo",
    "province": "Ituri",
    "city": "Luna",
    "lat": 0.8883,
    "lng": 29.6126,
    "type": "violence-civilians",
    "severity": "high",
    "fatalities": 12,
    "actor1": "NALU: National Army for the Liberation of Uganda",
    "actor2": "Civilians (Democratic Republic of Congo)",
    "title": "Police inspector of Ituri District announced today that twelve people were killed when three vehicles in which they were travelling were ambushed yest",
    "desc": "Police inspector of Ituri District announced today that twelve people were killed when three vehicles in which they were travelling were ambushed yesterday by the Ugandan rebels of the Alliance for Democratic Front/National Army for the Liberation of Uganda near Luna location. The vehicles were travelling from Bunia town in Orientale Province to Beni location in Nord Kivu Province. (来源: ACLED, 事件ID: DRC4954)",
    "source": "ACLED",
    "sourceUrl": "https://acleddata.com/data/",
    "verified": true
  }
];
